"""Token Tracker arayüz çevirileri — LANGS ile bire bir."""

from __future__ import annotations

import re

from lang_packs_data import PACKS
from meter_texts import METER

_PCT_N = re.compile(r"\{n:\.\d+f\}")


def _plain_pct_n(text: str) -> str:
    return _PCT_N.sub("{n}", text)


REQUIRED = (
    "title", "hello", "version", "version_long", "error", "empty", "no_data",
    "refresh", "close", "hide_tray", "ideas", "tips_nav", "agents_nav", "github_nav", "usage", "settings",
    "lang_label", "theme_label", "interval_label", "pin_label", "pin_hint",
    "boot_label", "boot_hint", "quota_label", "quota_hint", "chat_label", "chat_hint",
    "consent_title", "consent_body", "consent_enable", "consent_later",
    "license_title", "license_body", "license_view", "license_accept", "license_reject",
    "license_missing",
    "usage_need_quota", "ideas_need_chat", "usage_summary", "usage_order_hint",
    "usage_order_up", "usage_order_down", "usage_crit_first", "usage_hide", "usage_hide_menu", "usage_unhide",
    "usage_hidden_hint", "usage_checked", "tray_lowest", "warn_label", "crit_label", "pct_decimals_label",
    "left_short", "model_label", "tokens_used", "tokens_used_turn", "spend_used", "spend_only",
    "show", "quit", "tray_hide",
    "ideas_wait", "ideas_none", "ideas_prompt", "ideas_fix", "ideas_all",
    "ideas_warn", "ideas_danger", "ideas_info", "ideas_look", "ideas_copied", "ideas_opened", "loading",
    "ideas_detail_title", "ideas_detail_back", "ideas_detail_problem", "ideas_detail_cause",
    "ideas_detail_solution", "ideas_detail_example", "ideas_detail_info_cause", "ideas_detail_info_solution",
    "ideas_detail_suggest", "ideas_detail_copy", "ideas_count", "ideas_clear", "ideas_filter_empty",
    "tips_title", "tips_hint", "tips_card_title", "tips_card_source", "tips_findings_title", "tips_detail_cause",
    "tip_paste_p", "tip_paste_f", "tip_vague_p", "tip_vague_f", "tip_dup_p", "tip_dup_f",
    "tip_focus_p", "tip_focus_f", "tip_rebuild_p", "tip_rebuild_f", "tip_path_p", "tip_path_f",
    "tip_session_p", "tip_session_f", "tip_mcp_p", "tip_mcp_f", "tip_skill_p", "tip_skill_f",
    "tip_baseline_p", "tip_baseline_f",
    "suggest_paste", "suggest_vague", "suggest_nofile", "suggest_rewrite", "suggest_split",
    "suggest_rebuild", "suggest_dup", "suggest_helper",
    "stat_chats", "stat_tok", "stat_tools", "stat_l_chat", "stat_l_tok", "stat_l_tools",
    "left",
    "issue_paste_p", "issue_paste_f", "issue_paste_c", "issue_vague_p", "issue_vague_f", "issue_vague_c",
    "issue_rewrite_p", "issue_rewrite_f", "issue_rewrite_c", "issue_split_p", "issue_split_f", "issue_split_c",
    "issue_nofile_p", "issue_nofile_f", "issue_nofile_c", "issue_rebuild_p", "issue_rebuild_f", "issue_rebuild_c",
    "issue_dup_p", "issue_dup_f", "issue_dup_c", "issue_helper_p", "issue_helper_f", "issue_helper_c",
    "theme_night", "theme_frost", "theme_aurora", "theme_ember",
    "interval_5", "interval_30", "interval_60", "interval_300",
    "usage_drop",
    "live_tip_on", "live_tip_busy", "live_tip_idle", "live_tip_err",
    "weekly_title", "weekly_hint", "weekly_pros", "weekly_cons", "weekly_agents",
    "weekly_fit", "weekly_partial", "weekly_gap", "weekly_open",
    "weekly_cat_all", "weekly_rank", "weekly_top_heading", "weekly_cat_heading",
    "weekly_cat_mcp", "weekly_cat_ide", "weekly_cat_cli", "weekly_cat_rules", "weekly_cat_tools", "weekly_cat_learn",
    "gh_open_web", "gh_open_hint", "gh_loading", "gh_no_desc", "gh_stars",
    "gh_source_live", "gh_source_cache", "gh_source_fallback",
    "gh_price_free", "gh_price_partial", "gh_price_paid", "gh_price_unknown", "gh_price_hint",
    "gh_detail_what", "gh_detail_adv", "gh_detail_download", "gh_detail_terminal", "gh_detail_mcp", "gh_detail_extra",
    "install_terminal", "install_agent", "install_checking", "install_pick_folder",
    "install_confirm_title", "install_confirm_body", "install_started", "install_launch_failed",
    "install_missing_tools", "install_need_agent", "install_no_option", "install_ready_terminal",
    "install_target_exists", "install_bad_repo", "install_bad_folder", "install_bad_arg",
    "install_bad_agent", "install_no_terminal", "install_pick_agent", "install_cancel",
    "agent_detail_menu", "agent_story_title", "agent_story_first", "agent_story_sessions",
    "agent_story_msgs", "agent_story_tools", "agent_story_tokens", "agent_story_freq",
    "agent_story_days", "agent_story_recent", "agent_story_need_chat", "agent_story_empty",
    "agent_story_trunc", "agents_title", "agents_hint", "agents_empty", "agents_kit_title", "agents_readonly",
    "agents_kind_rule", "agents_kind_ext", "agents_kind_skill", "agents_kind_mcp", "agents_kind_plugin",
) + (
    "adv_status_crit", "adv_status_warn", "adv_status_err", "adv_status_ok",
    "adv_band_danger", "adv_band_warn", "adv_band_info",
    "adv_err_session", "adv_plan", "adv_story_tokens", "adv_cursor_rules_trim",
    "adv_cursor_crit", "adv_cursor_warn", "adv_cursor_ok", "adv_cursor_mcp_many", "adv_cursor_mcp_use",
    "adv_cursor_long_chat", "adv_cursor_tool",
    "adv_codex_crit", "adv_codex_warn", "adv_codex_ok", "adv_codex_mcp_many", "adv_codex_mcp_use",
    "adv_codex_long_chat", "adv_codex_tool",
    "adv_claude_crit", "adv_claude_warn", "adv_claude_ok", "adv_claude_mcp_many", "adv_claude_mcp_use",
    "adv_claude_long_chat", "adv_claude_tool",
    "adv_copilot_crit", "adv_copilot_warn", "adv_copilot_ok", "adv_copilot_mcp_many", "adv_copilot_mcp_use",
    "adv_copilot_long_chat", "adv_copilot_tool",
    "adv_gemini_crit", "adv_gemini_warn", "adv_gemini_ok", "adv_gemini_mcp_many", "adv_gemini_mcp_use",
    "adv_gemini_long_chat", "adv_gemini_tool",
    "adv_local_crit", "adv_local_warn", "adv_local_ok", "adv_local_mcp_many", "adv_local_mcp_use",
    "adv_local_long_chat", "adv_local_tool",
    "adv_manus_crit", "adv_manus_warn", "adv_manus_ok", "adv_manus_mcp_many", "adv_manus_mcp_use",
    "adv_manus_long_chat", "adv_manus_tool",
    "adv_generic_crit", "adv_generic_warn", "adv_generic_ok", "adv_generic_mcp_many", "adv_generic_mcp_use",
    "adv_generic_long_chat", "adv_generic_tool",
)


def validate_langs(codes: set[str]) -> None:
    for code in codes:
        assert code in TEXTS, code
        missing = set(REQUIRED) - set(TEXTS[code])
        assert not missing, (code, missing)


def _finish(pack: dict[str, str]) -> dict[str, str]:
    pack.setdefault("title", "Token Tracker")
    pack.setdefault("version", "v{v}")
    pack.setdefault("error", "error")
    pack.setdefault("loading", "Loading…")
    pack.setdefault("ideas_danger", "Critical")
    pack.setdefault("quota_label", TEXTS_FALLBACK_EN["quota_label"])
    pack.setdefault("quota_hint", TEXTS_FALLBACK_EN["quota_hint"])
    pack.setdefault("chat_label", TEXTS_FALLBACK_EN["chat_label"])
    pack.setdefault("chat_hint", TEXTS_FALLBACK_EN["chat_hint"])
    pack.setdefault("consent_title", TEXTS_FALLBACK_EN["consent_title"])
    pack.setdefault("consent_body", TEXTS_FALLBACK_EN["consent_body"])
    pack.setdefault("consent_enable", TEXTS_FALLBACK_EN["consent_enable"])
    pack.setdefault("consent_later", TEXTS_FALLBACK_EN["consent_later"])
    pack.setdefault("license_title", TEXTS_FALLBACK_EN["license_title"])
    pack.setdefault("license_body", TEXTS_FALLBACK_EN["license_body"])
    pack.setdefault("license_view", TEXTS_FALLBACK_EN["license_view"])
    pack.setdefault("license_accept", TEXTS_FALLBACK_EN["license_accept"])
    pack.setdefault("license_reject", TEXTS_FALLBACK_EN["license_reject"])
    pack.setdefault("license_missing", TEXTS_FALLBACK_EN["license_missing"])
    pack.setdefault("usage_need_quota", TEXTS_FALLBACK_EN["usage_need_quota"])
    pack.setdefault("ideas_need_chat", TEXTS_FALLBACK_EN["ideas_need_chat"])
    pack.setdefault("usage_summary", TEXTS_FALLBACK_EN["usage_summary"])
    pack.setdefault("usage_order_hint", TEXTS_FALLBACK_EN["usage_order_hint"])
    pack.setdefault("usage_order_up", TEXTS_FALLBACK_EN["usage_order_up"])
    pack.setdefault("usage_order_down", TEXTS_FALLBACK_EN["usage_order_down"])
    pack.setdefault("usage_crit_first", TEXTS_FALLBACK_EN["usage_crit_first"])
    pack.setdefault("usage_hide", TEXTS_FALLBACK_EN["usage_hide"])
    pack.setdefault("usage_hide_menu", TEXTS_FALLBACK_EN["usage_hide_menu"])
    pack.setdefault("usage_unhide", TEXTS_FALLBACK_EN["usage_unhide"])
    pack.setdefault("usage_hidden_hint", TEXTS_FALLBACK_EN["usage_hidden_hint"])
    pack.setdefault("usage_checked", TEXTS_FALLBACK_EN["usage_checked"])
    pack.setdefault("tray_lowest", TEXTS_FALLBACK_EN["tray_lowest"])
    pack.setdefault("warn_label", TEXTS_FALLBACK_EN["warn_label"])
    pack.setdefault("crit_label", TEXTS_FALLBACK_EN["crit_label"])
    pack.setdefault("pct_decimals_label", TEXTS_FALLBACK_EN["pct_decimals_label"])
    pack.setdefault("left_short", TEXTS_FALLBACK_EN["left_short"])
    pack.setdefault("model_label", TEXTS_FALLBACK_EN["model_label"])
    pack.setdefault("tokens_used", TEXTS_FALLBACK_EN["tokens_used"])
    pack.setdefault("tokens_used_turn", TEXTS_FALLBACK_EN["tokens_used_turn"])
    pack.setdefault("spend_used", TEXTS_FALLBACK_EN["spend_used"])
    pack.setdefault("spend_only", TEXTS_FALLBACK_EN["spend_only"])
    pack.setdefault("ideas_copied", TEXTS_FALLBACK_EN["ideas_copied"])
    pack.setdefault("ideas_opened", TEXTS_FALLBACK_EN["ideas_opened"])
    pack.setdefault("ideas_detail_title", TEXTS_FALLBACK_EN["ideas_detail_title"])
    pack.setdefault("ideas_detail_back", TEXTS_FALLBACK_EN["ideas_detail_back"])
    pack.setdefault("ideas_detail_problem", TEXTS_FALLBACK_EN["ideas_detail_problem"])
    pack.setdefault("ideas_detail_cause", TEXTS_FALLBACK_EN["ideas_detail_cause"])
    pack.setdefault("ideas_detail_solution", TEXTS_FALLBACK_EN["ideas_detail_solution"])
    pack.setdefault("ideas_detail_example", TEXTS_FALLBACK_EN["ideas_detail_example"])
    pack.setdefault("ideas_detail_info_cause", TEXTS_FALLBACK_EN["ideas_detail_info_cause"])
    pack.setdefault("ideas_detail_info_solution", TEXTS_FALLBACK_EN["ideas_detail_info_solution"])
    pack.setdefault("ideas_detail_suggest", TEXTS_FALLBACK_EN["ideas_detail_suggest"])
    pack.setdefault("ideas_detail_copy", TEXTS_FALLBACK_EN["ideas_detail_copy"])
    pack.setdefault("ideas_count", TEXTS_FALLBACK_EN["ideas_count"])
    pack.setdefault("ideas_clear", TEXTS_FALLBACK_EN["ideas_clear"])
    pack.setdefault("ideas_filter_empty", TEXTS_FALLBACK_EN["ideas_filter_empty"])
    pack.setdefault("tips_nav", TEXTS_FALLBACK_EN["tips_nav"])
    for _k in (
        "agents_nav", "github_nav", "weekly_title", "weekly_hint", "weekly_pros", "weekly_cons", "weekly_agents",
        "weekly_fit", "weekly_partial", "weekly_gap", "weekly_open",
        "weekly_cat_all", "weekly_rank", "weekly_top_heading", "weekly_cat_heading",
        "weekly_cat_mcp", "weekly_cat_ide", "weekly_cat_cli", "weekly_cat_rules", "weekly_cat_tools", "weekly_cat_learn",
        "gh_open_web", "gh_open_hint", "gh_loading", "gh_no_desc", "gh_stars",
        "gh_source_live", "gh_source_cache", "gh_source_fallback",
        "gh_price_free", "gh_price_partial", "gh_price_paid", "gh_price_unknown", "gh_price_hint",
        "gh_detail_what", "gh_detail_adv", "gh_detail_download", "gh_detail_terminal", "gh_detail_mcp", "gh_detail_extra",
        "install_terminal", "install_agent", "install_checking", "install_pick_folder",
        "install_confirm_title", "install_confirm_body", "install_started", "install_launch_failed",
        "install_missing_tools", "install_need_agent", "install_no_option", "install_ready_terminal",
        "install_target_exists", "install_bad_repo", "install_bad_folder", "install_bad_arg",
        "install_bad_agent", "install_no_terminal", "install_pick_agent", "install_cancel",
        "agent_detail_menu", "agent_story_title", "agent_story_first", "agent_story_sessions",
        "agent_story_msgs", "agent_story_tools", "agent_story_tokens", "agent_story_freq",
        "agent_story_days", "agent_story_recent", "agent_story_need_chat", "agent_story_empty",
        "agent_story_trunc", "agents_title", "agents_hint", "agents_empty", "agents_kit_title", "agents_readonly",
        "agents_kind_rule", "agents_kind_ext", "agents_kind_skill", "agents_kind_mcp", "agents_kind_plugin",
    ):
        pack.setdefault(_k, TEXTS_FALLBACK_EN[_k])
    for _k in REQUIRED:
        if _k.startswith("adv_"):
            pack.setdefault(_k, TEXTS_FALLBACK_EN[_k])
    pack.setdefault("interval_5", TEXTS_FALLBACK_EN["interval_5"])
    pack.setdefault("usage_drop", TEXTS_FALLBACK_EN["usage_drop"])
    pack.setdefault("live_tip_on", TEXTS_FALLBACK_EN["live_tip_on"])
    pack.setdefault("live_tip_busy", TEXTS_FALLBACK_EN["live_tip_busy"])
    pack.setdefault("live_tip_idle", TEXTS_FALLBACK_EN["live_tip_idle"])
    pack.setdefault("live_tip_err", TEXTS_FALLBACK_EN["live_tip_err"])
    for key in (
        "tips_title", "tips_hint", "tips_card_title", "tips_card_source", "tips_findings_title", "tips_detail_cause",
        "tip_paste_p", "tip_paste_f", "tip_vague_p", "tip_vague_f", "tip_dup_p", "tip_dup_f",
        "tip_focus_p", "tip_focus_f", "tip_rebuild_p", "tip_rebuild_f", "tip_path_p", "tip_path_f",
        "tip_session_p", "tip_session_f", "tip_mcp_p", "tip_mcp_f", "tip_skill_p", "tip_skill_f",
        "tip_baseline_p", "tip_baseline_f",
    ):
        pack.setdefault(key, TEXTS_FALLBACK_EN[key])
    for stem in ("paste", "vague", "nofile", "rewrite", "split", "rebuild", "dup", "helper"):
        pack.setdefault(f"suggest_{stem}", TEXTS_FALLBACK_EN[f"suggest_{stem}"])
    for stem in (
        "paste", "vague", "rewrite", "split", "nofile", "rebuild", "dup", "helper",
    ):
        for sfx in ("p", "f", "c"):
            pack.setdefault(f"issue_{stem}_{sfx}", TEXTS_FALLBACK_EN[f"issue_{stem}_{sfx}"])
    for key in ("left", "left_short", "tray_lowest", "usage_drop"):
        if key in pack:
            pack[key] = _plain_pct_n(pack[key])
    return pack


TEXTS_FALLBACK_EN = {
    "quota_label": "Quota access",
    "quota_hint": "Reads local sessions and asks only that service’s official quota API. Tokens are not stored or sent to the developer.",
    "chat_label": "Chat analysis for Ideas",
    "chat_hint": "Scans known local chat folders on this PC only. Nothing is uploaded. Documents and whole disks are not scanned.",
    "consent_title": "Before you start",
    "consent_body": (
        "Token Tracker needs your permission to read local session and chat data on this PC.\n\n"
        "Quota: reads Cursor, Codex, Claude, Gemini, and GitHub Copilot session data and asks only "
        "each service’s official quota API. Tokens are not sent to the developer and are not stored.\n\n"
        "Ideas: scans known local chat folders on this PC only. Nothing is uploaded.\n\n"
        "You can turn these off later in Settings."
    ),
    "consent_enable": "Accept and enable",
    "consent_later": "Keep disabled for now",
    "license_title": "Before you start",
    "license_body": (
        "Before using Token Tracker, review and accept the Software License Agreement and allow "
        "local quota access and chat analysis.\n\n"
        "Quota: reads local session data and asks only each service’s official quota API. "
        "Tokens are not sent to the developer and are not stored.\n\n"
        "Ideas: scans known local chat folders on this PC only. Nothing is uploaded.\n\n"
        "You can turn these off later in Settings."
    ),
    "license_view": "View license text",
    "license_accept": "Accept and continue",
    "license_reject": "I do not accept — exit",
    "license_missing": "License text was not found, so the application cannot start.",
    "usage_need_quota": "Quota access is off. Enable it in Settings.",
    "ideas_need_chat": "Chat analysis is off. You can enable it in Settings.",
    "usage_summary": "{crit} critical · {ok} ok",
    "usage_order_hint": "Critical cards rise automatically. Drag to reorder (gap follows the pointer) · right-click to hide · tap for details.",
    "usage_order_up": "Move up",
    "usage_order_down": "Move down",
    "usage_crit_first": "Critical first",
    "usage_hide": "Hide",
    "usage_hide_menu": "Hide from list",
    "usage_unhide": "restore",
    "usage_hidden_hint": "{n} hidden — tap a name to restore",
    "usage_checked": "checked {t}",
    "tray_lowest": "{name}: {n}% left",
    "warn_label": "Warn below",
    "crit_label": "Critical below",
    "pct_decimals_label": "Percent decimals (X.YYYY)",
    "left_short": "{n}%",
    "model_label": "Model: {name}",
    "tokens_used": "Used: {used} tokens",
    "tokens_used_turn": "Used: {used} tokens · last turn {last}",
    "spend_used": "Spent: {used} · included {limit}",
    "spend_only": "Spent: {used}",
    "usage_drop": " (-{n})",
    "live_tip_on": "Live refresh on",
    "live_tip_busy": "Updating…",
    "live_tip_idle": "Waiting for next refresh",
    "live_tip_err": "Update failed",
    "ideas_copied": "Copied",
    "ideas_opened": "File opened",
    "ideas_detail_title": "Review",
    "ideas_detail_back": "Back",
    "ideas_detail_problem": "Problem",
    "ideas_detail_cause": "Why it happens",
    "ideas_detail_solution": "Solution",
    "ideas_detail_example": "Example from your chat",
    "ideas_detail_info_cause": "Detected from local chat analysis.",
    "ideas_detail_info_solution": "No action needed; this is informational.",
    "ideas_detail_suggest": "Suggested prompt",
    "ideas_detail_copy": "Copy",
    "ideas_count": "{n}×",
    "ideas_clear": "No notable issues. Scanned {chats} sessions, ~{tokens} tokens.",
    "ideas_filter_empty": "No items match this filter.",
    "tips_nav": "Agent tips",
    "agents_nav": "Agents",
    "github_nav": "GitHub",
    "weekly_title": "GitHub Top 100",
    "weekly_hint": "Live list from GitHub (cached). Tap a row for install details — use “Open on the web” for the repo URL.",
    "weekly_pros": "Pros: {text}",
    "weekly_cons": "Cons: {text}",
    "weekly_agents": "Works with: {agents}",
    "weekly_fit": "Fits you",
    "weekly_partial": "Partial",
    "weekly_gap": "New",
    "weekly_open": "Open on GitHub",
    "weekly_cat_all": "Top 100",
    "weekly_rank": "#{n}",
    "weekly_top_heading": "Top {n}",
    "weekly_cat_heading": "{cat} · {n}",
    "weekly_cat_mcp": "MCP",
    "weekly_cat_ide": "IDE",
    "weekly_cat_cli": "Terminal",
    "weekly_cat_rules": "Rules",
    "weekly_cat_tools": "Tools",
    "weekly_cat_learn": "Learn",
    "gh_open_web": "Open on the web",
    "gh_open_hint": "Details stay in the app. Tap “Open on the web” only when you want the GitHub page.",
    "gh_loading": "Loading projects…",
    "gh_no_desc": "No description yet.",
    "gh_stars": "★ {n}",
    "gh_source_live": "Live",
    "gh_source_cache": "Cached",
    "gh_source_fallback": "Offline pack",
    "gh_price_free": "Free",
    "gh_price_partial": "Partly paid",
    "gh_price_paid": "Paid",
    "gh_price_unknown": "Unknown",
    "gh_price_hint": "Estimated from the GitHub license and description. External APIs or services may still cost money.",
    "gh_detail_what": "What it does",
    "gh_detail_adv": "Advantages",
    "gh_detail_download": "How to download",
    "gh_detail_terminal": "Terminal install",
    "gh_detail_mcp": "MCP setup",
    "gh_detail_extra": "Extra tips",
    "install_terminal": "Install in terminal",
    "install_agent": "Install with agent",
    "install_checking": "Checking install requirements…",
    "install_pick_folder": "Choose the parent folder for the clone",
    "install_confirm_title": "Start install?",
    "install_confirm_body": "Repository: {repo}\nTarget: {target}\n\nCommands:\n{commands}\n\nWarning: installing a repository can run third-party code. Review the commands above. A visible PowerShell window will open; Token Tracker only starts the process and does not assume success.",
    "install_started": "Install started in a new terminal window. Watch that window for progress.",
    "install_launch_failed": "Could not start the install window.",
    "install_missing_tools": "A known install recipe was found, but required tools are missing: {tools}.",
    "install_need_agent": "No direct safe terminal recipe for this repo. You can start an install task in a local agent CLI.",
    "install_no_option": "No safe terminal recipe and no supported agent CLI (agent, claude, codex, gemini) was found.",
    "install_ready_terminal": "Verified root manifest and required tools — terminal install is available.",
    "install_target_exists": "That folder already exists. Choose another parent folder so nothing is overwritten.",
    "install_bad_repo": "Only verified github.com/owner/repo addresses are allowed.",
    "install_bad_folder": "Choose a valid empty parent folder on this PC.",
    "install_bad_arg": "Rejected an unsafe path or command argument.",
    "install_bad_agent": "That agent CLI is not available or uses unsafe flags.",
    "install_no_terminal": "Terminal install is not available for this project.",
    "install_pick_agent": "Choose an agent CLI",
    "install_cancel": "Cancel",
    "agent_detail_menu": "Agent details",
    "agent_story_title": "{name} usage summary",
    "agent_story_first": "First seen: {date}",
    "agent_story_sessions": "Local conversations: {n}",
    "agent_story_msgs": "Your messages: {n}",
    "agent_story_tools": "Tool calls: {n}",
    "agent_story_tokens": "Approx. tokens: {n}",
    "agent_story_freq": "Pace: ~{n}/week",
    "agent_story_days": "Active days: {n}",
    "agent_story_recent": "Recent work",
    "agent_story_need_chat": "Turn on chat analysis in Settings to see session history.",
    "agent_story_empty": "Cloud conversation history is not accessible.",
    "agent_story_trunc": "Sample of recent sessions (not full lifetime).",
    "agents_title": "Agents",
    "agents_hint": "Tap a logo to see that provider’s quota and local conversation count.",
    "agents_empty": "No agents found yet.",
    "agents_kit_title": "Rules & extensions",
    "agents_readonly": "View only — edit rules/extensions in the agent itself.",
    "agents_kind_rule": "Rules",
    "agents_kind_ext": "Extensions",
    "agents_kind_skill": "Skills",
    "agents_kind_mcp": "MCP",
    "agents_kind_plugin": "Plugins",
    "tips_title": "Token tips for this agent",
    "tips_hint": "Personal advice from remaining quota, plan, tools and habits.",
    "tips_card_title": "Token tip",
    "tips_card_source": "Saving tip",
    "tips_findings_title": "From your chats",
    "tips_detail_cause": "These habits cut repeated context and tool loops — the main token burn.",
    "adv_status_crit": "Critical quota",
    "adv_status_warn": "Low quota",
    "adv_status_err": "Session issue",
    "adv_status_ok": "Healthy",
    "adv_band_danger": "Only ~{pct}% left — treat this agent as scarce.",
    "adv_band_warn": "About {pct}% left — tighten prompts on this agent.",
    "adv_band_info": "About {pct}% left — room to work; still stay sharp.",
    "adv_err_session": "Quota read failed — re-open the app / sign in before relying on meters.",
    "adv_plan": "Plan: {plan}. Match model size to the task.",
    "adv_story_tokens": "Recent local chats ≈ {n} tokens — start fresh threads for new jobs.",
    "adv_cursor_rules_trim": "You have {n} rule files — long rules reload every turn; keep only what you need.",
    "adv_cursor_crit": "Cursor: stop Agent/auto loops. Ask one file + one change. Prefer Ask mode or a smaller model until reset.",
    "adv_cursor_warn": "Cursor: @-mention exact files instead of @Codebase. Short Composer turns beat long Agent runs.",
    "adv_cursor_ok": "Cursor: keep .cursorrules short; path + expected result beats pasting whole files.",
    "adv_cursor_mcp_many": "Cursor: {n} MCP servers attached — disable idle ones; each tool schema burns context.",
    "adv_cursor_mcp_use": "Cursor: call MCP “{name}” by name instead of broad search loops.",
    "adv_cursor_long_chat": "Cursor: this chat got long — new Agent chat for the next feature.",
    "adv_cursor_tool": "Cursor: “{tool}” dominates — point to exact paths to cut tool churn.",
    "adv_codex_crit": "Codex/ChatGPT: pause multi-file refactors. One patch request; paste only the failing hunk.",
    "adv_codex_warn": "Codex: Prefer smaller reasoning for simple edits; save deep reasoning for hard bugs.",
    "adv_codex_ok": "Codex: give repo path + failing test; avoid dumping entire files into the thread.",
    "adv_codex_mcp_many": "Codex: {n} tools/MCP — turn off unused connectors for this session.",
    "adv_codex_mcp_use": "Codex: use “{name}” directly when it fits; don’t re-explain the same search.",
    "adv_codex_long_chat": "Codex: open a new chat for a new task so old patches aren’t reloaded.",
    "adv_codex_tool": "Codex: heavy “{tool}” use — narrow the scope in the next prompt.",
    "adv_claude_crit": "Claude: switch to a lighter model / shorter Projects context. One artifact at a time.",
    "adv_claude_warn": "Claude: trim Project knowledge; long system context repeats every message.",
    "adv_claude_ok": "Claude: point to files; ask for a diff-sized reply, not a full rewrite.",
    "adv_claude_mcp_many": "Claude: {n} MCP tools — disable extras in Desktop/settings for this job.",
    "adv_claude_mcp_use": "Claude: invoke “{name}” instead of pasting browser/docs dumps.",
    "adv_claude_long_chat": "Claude: start a new conversation; long threads re-send huge history.",
    "adv_claude_tool": "Claude: “{tool}” is frequent — constrain paths and stop after one pass.",
    "adv_copilot_crit": "Copilot: use inline completions for tiny edits; save Chat for hard questions only.",
    "adv_copilot_warn": "Copilot: @workspace sparingly — name the file. Slash commands beat essay prompts.",
    "adv_copilot_ok": "Copilot: accept small completions; reject noisy suggestions so you don’t re-prompt.",
    "adv_copilot_mcp_many": "Copilot/VS Code: {n} MCP — fewer tools, clearer Chat answers.",
    "adv_copilot_mcp_use": "Copilot: lean on “{name}” when it covers the lookup.",
    "adv_copilot_long_chat": "Copilot Chat: new thread per bug — old context burns premium requests.",
    "adv_copilot_tool": "Copilot: “{tool}” heavy — ask with a single file reference next.",
    "adv_gemini_crit": "Gemini: shorten context windows; one file + error log, not the whole repo.",
    "adv_gemini_warn": "Gemini: prefer CLI/file refs over pasting; keep chats task-scoped.",
    "adv_gemini_ok": "Gemini: clear goal + path; avoid re-sending the same attachment.",
    "adv_gemini_mcp_many": "Gemini: {n} tools attached — drop unused ones for this run.",
    "adv_gemini_mcp_use": "Gemini: call “{name}” explicitly when needed.",
    "adv_gemini_long_chat": "Gemini: new chat for new work — long history is expensive.",
    "adv_gemini_tool": "Gemini: “{tool}” loops — tighten the question.",
    "adv_local_crit": "Local model: context full? Shrink context length / unload big models; quota here is RAM/time.",
    "adv_local_warn": "Local: smaller model for edits; save large models for hard reasoning.",
    "adv_local_ok": "Local: short prompts + file paths; you control cost by context size.",
    "adv_local_mcp_many": "Local: {n} tools still add prompt overhead — keep the set small.",
    "adv_local_mcp_use": "Local: use “{name}” when it replaces a long paste.",
    "adv_local_long_chat": "Local: clear or restart the session when replies slow down.",
    "adv_local_tool": "Local: “{tool}” repeats — batch the request once.",
    "adv_manus_crit": "Manus: pause broad browser/agent loops; one concrete goal per run.",
    "adv_manus_warn": "Manus: limit open tabs/tools; reuse results instead of re-crawling.",
    "adv_manus_ok": "Manus: name the site/task; avoid open-ended “explore everything”.",
    "adv_manus_mcp_many": "Manus: {n} connectors — disable idle ones.",
    "adv_manus_mcp_use": "Manus: prefer “{name}” for the next lookup.",
    "adv_manus_long_chat": "Manus: new run for a new goal.",
    "adv_manus_tool": "Manus: “{tool}” is hot — narrow the target.",
    "adv_generic_crit": "Quota is critical — one short ask, one file, then wait for reset.",
    "adv_generic_warn": "Quota is low — cut pastes and multi-step agent runs.",
    "adv_generic_ok": "Stay concise: path + change + expected result.",
    "adv_generic_mcp_many": "{n} tools attached — disable what you are not using.",
    "adv_generic_mcp_use": "Call “{name}” by name instead of long manual search.",
    "adv_generic_long_chat": "Start a fresh chat for the next task.",
    "adv_generic_tool": "“{tool}” is frequent — point to exact paths.",
    "tip_paste_p": "Stop pasting large files into chat.",
    "tip_paste_f": "Give a path; ask the agent to read only the needed lines.",
    "tip_vague_p": "Vague asks force long search loops.",
    "tip_vague_f": "Name file + error + expected result in one short message.",
    "tip_dup_p": "Repeating the same prompt reloads unchanged context.",
    "tip_dup_f": "Send only what changed since the last message.",
    "tip_focus_p": "Multi-job or rewrite-all prompts waste tokens.",
    "tip_focus_f": "One task per message; one file when possible.",
    "tip_rebuild_p": "Build/deploy on every step burns quota.",
    "tip_rebuild_f": "Change the code first; build once when finished.",
    "tip_path_p": "Broad Read/Grep/Shell loops showed up often.",
    "tip_path_f": "Point to the exact file; avoid repeating {tools}.",
    "tip_session_p": "A chat session grew very long.",
    "tip_session_f": "Start a fresh chat for a new task so old context is not reloaded.",
    "tip_mcp_p": "MCP “{name}” is available — call it by name.",
    "tip_mcp_f": "Write: use {name} MCP for … (skip a long manual search).",
    "tip_skill_p": "Skill “{name}” can short-circuit this work.",
    "tip_skill_f": "Write: follow the {name} skill.",
    "tip_baseline_p": "Keep prompts short and single-purpose.",
    "tip_baseline_f": "Path + one change + expected result. No full pastes, no “redo everything”.",
    "suggest_paste": "File path: `{path}` — read the relevant lines from disk; do not paste the full content.",
    "suggest_vague": "File: … — Error: … — Expected: …\n(Context: {snippet})",
    "suggest_nofile": "In `{path}`: {snippet}",
    "suggest_rewrite": "Change only `{path}`: describe one focused edit.",
    "suggest_split": "First task only: … (I will send the rest in a separate message.)",
    "suggest_rebuild": "Make the code change; run build/deploy once at the end.",
    "suggest_dup": "Since my last message, only this changed: …",
    "suggest_helper": "Use the {helper} skill: {snippet}",
    "issue_paste_p": "Huge paste burns tokens.",
    "issue_paste_f": "Give a file path; do not paste the whole content.",
    "issue_paste_c": "Large pasted text makes the model re-process every token.",
    "issue_vague_p": "The request is vague.",
    "issue_vague_f": "Name the file, the error, and the expected result.",
    "issue_vague_c": "Without file, error, or expected outcome the model guesses wrong.",
    "issue_rewrite_p": "Rewrite-all is costly.",
    "issue_rewrite_f": "Ask for one file or one focused change.",
    "issue_rewrite_c": "Broad rewrite requests touch many files at once.",
    "issue_split_p": "Several jobs in one message.",
    "issue_split_f": "Split into separate prompts.",
    "issue_split_c": "Multiple tasks in one prompt mix contexts and waste tokens.",
    "issue_nofile_p": "No file path in the request.",
    "issue_nofile_f": "Name the file or folder you mean.",
    "issue_nofile_c": "Code questions without a path force the model to search blindly.",
    "issue_rebuild_p": "Build requested at every step.",
    "issue_rebuild_f": "Build once when the work is finished.",
    "issue_rebuild_c": "Repeated build/deploy requests add slow loops to each reply.",
    "issue_dup_p": "Same prompt sent again.",
    "issue_dup_f": "Send only what changed since last time.",
    "issue_dup_c": "Repeating the same message re-processes unchanged context.",
    "issue_helper_p": "A helper skill could do this.",
    "issue_helper_f": "Name it: {helpers}",
    "issue_helper_c": "A matching skill or MCP exists but was not invoked.",
    "interval_5": "Live",
}

TEXTS: dict[str, dict[str, str]] = {
    "tr": _finish({
        "title": "Token Tracker", "hello": "Hoş geldin, {name}", "version": "v{v}", "version_long": "Sürüm {v}",
        "error": "hata", "empty": "Kurulu yapay zeka yok", "no_data": "Veri yok", "refresh": "Yenile",
        "close": "Kapat", "hide_tray": "Tepsiye küçült", "ideas": "Öneriler", "tips_nav": "Ajan ipuçları",
        "agents_nav": "Ajanlar",
        "github_nav": "GitHub",
        "weekly_title": "GitHub Top 100",
        "weekly_hint": "GitHub’dan canlı liste (önbellekli). Satıra bas → kurulum detayı. Adrese gitmek için “İnternet adresine git”.",
        "weekly_pros": "Artı: {text}",
        "weekly_cons": "Eksi: {text}",
        "weekly_agents": "Çalıştığı ajanlar: {agents}",
        "weekly_fit": "Sana uyuyor",
        "weekly_partial": "Kısmen",
        "weekly_gap": "Yeni",
        "weekly_open": "GitHub’da aç",
        "weekly_cat_all": "Top 100",
        "weekly_rank": "#{n}",
        "weekly_top_heading": "Top {n}",
        "weekly_cat_heading": "{cat} · {n}",
        "weekly_cat_mcp": "MCP",
        "weekly_cat_ide": "IDE",
        "weekly_cat_cli": "Terminal",
        "weekly_cat_rules": "Kurallar",
        "weekly_cat_tools": "Araçlar",
        "weekly_cat_learn": "Öğren",
        "gh_open_web": "İnternet adresine git",
        "gh_open_hint": "Detaylar uygulamada kalır. GitHub sayfası için yalnızca “İnternet adresine git”e bas.",
        "gh_loading": "Projeler yükleniyor…",
        "gh_no_desc": "Açıklama henüz yok.",
        "gh_stars": "★ {n}",
        "gh_source_live": "Canlı",
        "gh_source_cache": "Önbellek",
        "gh_source_fallback": "Çevrimdışı paket",
        "gh_price_free": "Ücretsiz",
        "gh_price_partial": "Kısmen ücretli",
        "gh_price_paid": "Ücretli",
        "gh_price_unknown": "Bilinmiyor",
        "gh_price_hint": "GitHub lisansı ve açıklamasından tahmin edilir. Harici API veya hizmetler ayrıca ücretli olabilir.",
        "gh_detail_what": "Ne işe yarar",
        "gh_detail_adv": "Avantajları",
        "gh_detail_download": "Nasıl indirilir",
        "gh_detail_terminal": "Terminal kurulumu",
        "gh_detail_mcp": "MCP kurulumu",
        "gh_detail_extra": "Ek notlar",
        "install_terminal": "Terminalde kur",
        "install_agent": "Ajan ile kur",
        "install_checking": "Kurulum koşulları denetleniyor…",
        "install_pick_folder": "Klon için üst klasörü seç",
        "install_confirm_title": "Kurulum başlatılsın mı?",
        "install_confirm_body": "Depo: {repo}\nHedef: {target}\n\nKomutlar:\n{commands}\n\nUyarı: depo kurulumu üçüncü taraf kodu çalıştırabilir. Yukarıdaki komutları kontrol et. Görünür bir PowerShell penceresi açılacak; Token Tracker yalnız işlemi başlatır ve başarıyı varsaymaz.",
        "install_started": "Kurulum yeni bir terminal penceresinde başladı. İlerlemeyi o pencereden izle.",
        "install_launch_failed": "Kurulum penceresi açılamadı.",
        "install_missing_tools": "Bilinen bir kurulum tarifi var ama gerekli araçlar eksik: {tools}.",
        "install_need_agent": "Bu depo için doğrudan güvenli terminal tarifi yok. Kurulu bir ajan CLI ile kurulum görevi başlatabilirsin.",
        "install_no_option": "Güvenli terminal tarifi yok ve desteklenen ajan CLI (agent, claude, codex, gemini) bulunamadı.",
        "install_ready_terminal": "Kök manifest ve gerekli araçlar doğrulandı — terminal kurulumu kullanılabilir.",
        "install_target_exists": "Bu klasör zaten var. Üzerine yazmamak için başka bir üst klasör seç.",
        "install_bad_repo": "Yalnız doğrulanmış github.com/sahip/depo adresleri kabul edilir.",
        "install_bad_folder": "Bu bilgisayarda geçerli bir üst klasör seç.",
        "install_bad_arg": "Güvenli olmayan yol veya komut argümanı reddedildi.",
        "install_bad_agent": "Bu ajan CLI yok veya güvenli olmayan bayrak kullanıyor.",
        "install_no_terminal": "Bu proje için terminal kurulumu uygun değil.",
        "install_pick_agent": "Ajan CLI seç",
        "install_cancel": "İptal",
        "agent_detail_menu": "Ajan detayları",
        "agent_story_title": "{name} kullanım özeti",
        "agent_story_first": "İlk görülme: {date}",
        "agent_story_sessions": "Yerel konuşma: {n}",
        "agent_story_msgs": "Mesajların: {n}",
        "agent_story_tools": "Araç çağrısı: {n}",
        "agent_story_tokens": "Yaklaşık token: {n}",
        "agent_story_freq": "Tempo: ~{n}/hafta",
        "agent_story_days": "Aktif gün: {n}",
        "agent_story_recent": "Son işler",
        "agent_story_need_chat": "Oturum geçmişi için Ayarlar’dan sohbet analizini aç.",
        "agent_story_empty": "Bulut konuşma geçmişine erişilemiyor.",
        "agent_story_trunc": "Son oturumlardan örnek (tüm ömür değil).",
        "agents_title": "Ajanlar",
        "agents_hint": "Logoya bas — sağlayıcının kotasını ve yerel konuşma sayısını gör.",
        "agents_empty": "Henüz ajan bulunamadı.",
        "agents_kit_title": "Kurallar ve eklentiler",
        "agents_readonly": "Yalnız görüntüleme — düzenleme ajanın kendi ayarından.",
        "agents_kind_rule": "Kurallar",
        "agents_kind_ext": "Eklentiler",
        "agents_kind_skill": "Skill’ler",
        "agents_kind_mcp": "MCP",
        "agents_kind_plugin": "Plugin’ler",
        "usage": "Kota",
        "settings": "Ayarlar", "lang_label": "Dil",
        "theme_label": "Tema", "interval_label": "Yenileme sıklığı", "pin_label": "Üstte tut",
        "pin_hint": "Pencereyi diğer pencerelerin üstünde tutar", "boot_label": "Başlangıçta aç",
        "boot_hint": "Windows, macOS veya Linux başlangıç listesinde görünür",
        "quota_label": "Kota erişimi",
        "quota_hint": "Yerel oturumu okuyup yalnızca ilgili hizmetin resmî kota API’sine sorar. Token saklanmaz, geliştiriciye gitmez.",
        "chat_label": "Öneriler için sohbet analizi",
        "chat_hint": "Bilinen yerel sohbet klasörlerini yalnızca bu bilgisayarda tarar. İnternete gönderilmez. Documents veya tüm disk taranmaz.",
        "consent_title": "Başlamadan önce",
        "consent_body": (
            "Token Tracker, bu bilgisayardaki yerel oturum ve sohbet verilerini okumak için izninize ihtiyaç duyar.\n\n"
            "Kota: Cursor, Codex, Claude, Gemini ve GitHub Copilot oturumlarını okuyup yalnızca resmî kota API’lerine sorar. "
            "Token’lar geliştiriciye gitmez ve saklanmaz.\n\n"
            "Öneriler: bilinen yerel sohbet klasörlerini yalnızca bu bilgisayarda tarar. İnternete gönderilmez.\n\n"
            "Bunları istediğiniz zaman Ayarlar’dan kapatabilirsiniz."
        ),
        "consent_enable": "Kabul et ve aç",
        "consent_later": "Şimdilik kapalı bırak",
        "license_title": "Başlamadan önce",
        "license_body": (
            "Token Tracker’i kullanmadan önce Yazılım Kullanım Lisansı’nı inceleyip kabul edin; "
            "yerel kota erişimi ve sohbet analizine izin verin.\n\n"
            "Kota: yerel oturum verisini okuyup yalnızca ilgili hizmetin resmî kota API’sine sorar. "
            "Token’lar geliştiriciye gitmez ve saklanmaz.\n\n"
            "Öneriler: bilinen yerel sohbet klasörlerini yalnızca bu bilgisayarda tarar. İnternete gönderilmez.\n\n"
            "Bunları istediğiniz zaman Ayarlar’dan kapatabilirsiniz."
        ),
        "license_view": "Lisans metnini görüntüle",
        "license_accept": "Kabul et ve devam et",
        "license_reject": "Kabul etmiyorum ve çık",
        "license_missing": "Lisans metni bulunamadığı için uygulama başlatılamıyor.",
        "usage_need_quota": "Kota erişimi kapalı. Ayarlar’dan açınca kullanım bilgisi gelir.",
        "ideas_need_chat": "Sohbet analizi kapalı. Ayarlar’dan açabilirsiniz.",
        "usage_summary": "{crit} kritik · {ok} normal",
        "usage_order_hint": "Kritikler otomatik üste. Sürükle: boşluk fareyi izler · sağ tık Gizliye al · detay için tıkla.",
        "usage_order_up": "Yukarı taşı",
        "usage_order_down": "Aşağı taşı",
        "usage_crit_first": "Kritikler önce",
        "usage_hide": "Gizle",
        "usage_hide_menu": "Gizliye al",
        "usage_unhide": "geri al",
        "usage_hidden_hint": "{n} gizli — adını tıkla, geri gelsin",
        "usage_checked": "kontrol {t}",
        "tray_lowest": "{name}: %{n} kaldı",
        "warn_label": "Uyarı eşiği",
        "crit_label": "Kritik eşik",
        "pct_decimals_label": "Yüzde ondalık (X.YYYY)",
        "left_short": "%{n}",
        "model_label": "Model: {name}",
        "tokens_used": "Tüketilen: {used} token",
        "tokens_used_turn": "Tüketilen: {used} token · son tur {last}",
        "spend_used": "Harcanan: {used} · dahil {limit}",
        "spend_only": "Harcanan: {used}",
        "usage_drop": " (-{n})",
        "live_tip_on": "Canlı yenileme açık",
        "live_tip_busy": "Güncelleniyor…",
        "live_tip_idle": "Sonraki yenilemeyi bekliyor",
        "live_tip_err": "Güncelleme başarısız",
        "show": "Göster", "quit": "Çık",
        "tray_hide": "Tepside. Göster için tıkla.", "ideas_wait": "Bakılıyor", "ideas_none": "Kayıt yok",
        "ideas_prompt": "Yanlış prompt", "ideas_fix": "Doğrusu", "ideas_all": "Tümü", "ideas_warn": "Uyarı",
        "ideas_info": "Bilgi", "ideas_danger": "Kritik", "ideas_look": "İncele",
        "ideas_copied": "Kopyalandı", "ideas_opened": "Dosya açıldı",
        "ideas_detail_title": "İnceleme", "ideas_detail_back": "Geri",
        "ideas_detail_problem": "Problem", "ideas_detail_cause": "Neden oluyor",
        "ideas_detail_solution": "Çözüm", "ideas_detail_example": "Sohbetten örnek",
        "ideas_detail_info_cause": "Yerel sohbet analizinden tespit edildi.",
        "ideas_detail_info_solution": "Bilgi amaçlı; ek işlem gerekmez.",
        "ideas_detail_suggest": "Önerilen prompt", "ideas_detail_copy": "Kopyala",
        "ideas_count": "{n} kez",
        "ideas_clear": "Belirgin sorun yok. {chats} oturum, ~{tokens} token incelendi.",
        "ideas_filter_empty": "Bu filtrede kayıt yok.",
        "tips_title": "Bu ajan için token ipuçları",
        "tips_hint": "Kalan kota, plan, araçlar ve alışkanlığa göre şahsi öneri.",
        "tips_card_title": "Token ipucu",
        "tips_card_source": "Tasarruf ipucu",
        "tips_findings_title": "Sohbetlerinden",
        "tips_detail_cause": "Bu alışkanlıklar tekrarlayan bağlamı ve araç döngülerini keser — asıl token yakan budur.",
        "adv_status_crit": "Kritik kota",
        "adv_status_warn": "Düşük kota",
        "adv_status_err": "Oturum sorunu",
        "adv_status_ok": "İyi durumda",
        "adv_band_danger": "Yalnız ~%{pct} kaldı — bu ajanı kıt kaynak say.",
        "adv_band_warn": "Yaklaşık %{pct} kaldı — bu ajanda prompt’ları sıkı tut.",
        "adv_band_info": "Yaklaşık %{pct} kaldı — çalışmaya yer var; yine de net ol.",
        "adv_err_session": "Kota okunamadı — uygulamayı yeniden aç / oturum aç, sonra metreye güven.",
        "adv_plan": "Plan: {plan}. Model boyutunu işe göre seç.",
        "adv_story_tokens": "Yerel sohbet ≈ {n} token — yeni iş için yeni sohbet aç.",
        "adv_cursor_rules_trim": "{n} kural dosyan var — uzun kurallar her turda yüklenir; yalnız gerekli olanı bırak.",
        "adv_cursor_crit": "Cursor: Agent/otomatik döngüyü kes. Tek dosya + tek değişiklik. Reset’e kadar Ask veya küçük model.",
        "adv_cursor_warn": "Cursor: @Codebase yerine tam dosya @-mention. Kısa Composer, uzun Agent’tan daha ucuz.",
        "adv_cursor_ok": "Cursor: .cursorrules kısa tut; yol + beklenen sonuç, dosya yapıştırmaktan iyi.",
        "adv_cursor_mcp_many": "Cursor: {n} MCP bağlı — boşta olanları kapat; her araç şeması bağlam yer.",
        "adv_cursor_mcp_use": "Cursor: “{name}” MCP’yi adıyla çağır; geniş arama döngüsü yapma.",
        "adv_cursor_long_chat": "Cursor: sohbet uzadı — sonraki özellik için yeni Agent sohbeti.",
        "adv_cursor_tool": "Cursor: “{tool}” baskın — sonraki istekte tam yol ver, araç savurganlığını kes.",
        "adv_codex_crit": "Codex/ChatGPT: çok dosyalı refaktörü durdur. Tek yama iste; yalnız kırılan hunk’ı yapıştır.",
        "adv_codex_warn": "Codex: Basit düzenlemede hafif reasoning; derin reasoning’i zor bug’a sakla.",
        "adv_codex_ok": "Codex: repo yolu + başarısız test ver; tüm dosyayı thread’e dökme.",
        "adv_codex_mcp_many": "Codex: {n} araç/MCP — bu oturumda kullanılmayanları kapat.",
        "adv_codex_mcp_use": "Codex: uyuyorsa “{name}”i doğrudan kullan; aynı aramayı yeniden anlatma.",
        "adv_codex_long_chat": "Codex: yeni iş için yeni sohbet — eski yamalar yeniden yüklenmesin.",
        "adv_codex_tool": "Codex: “{tool}” ağır — sonraki prompt’ta kapsamı daralt.",
        "adv_claude_crit": "Claude: daha hafif model / kısa Project bağlamı. Bir seferde bir çıktı.",
        "adv_claude_warn": "Claude: Project knowledge’ı budar; uzun sistem bağlamı her mesajda tekrarlanır.",
        "adv_claude_ok": "Claude: dosyaya işaret et; tam yeniden yazım değil, diff boyutunda cevap iste.",
        "adv_claude_mcp_many": "Claude: {n} MCP — Desktop/ayarlarda fazlayı bu iş için kapat.",
        "adv_claude_mcp_use": "Claude: tarayıcı/docs yapıştırmak yerine “{name}”i çağır.",
        "adv_claude_long_chat": "Claude: yeni konuşma aç; uzun thread büyük geçmişi yeniden gönderir.",
        "adv_claude_tool": "Claude: “{tool}” sık — yolu sınırla, bir geçişte bırak.",
        "adv_copilot_crit": "Copilot: ufak işlerde satır içi öneri; Chat’i yalnız zor soruya sakla.",
        "adv_copilot_warn": "Copilot: @workspace’i seyrek kullan — dosya adı ver. Slash komut, uzun denemeden iyi.",
        "adv_copilot_ok": "Copilot: küçük öneriyi kabul et; gürültülü öneriyi reddet ki yeniden sormayasın.",
        "adv_copilot_mcp_many": "Copilot/VS Code: {n} MCP — az araç, net Chat.",
        "adv_copilot_mcp_use": "Copilot: aramayı “{name}” karşılıyorsa ona yaslan.",
        "adv_copilot_long_chat": "Copilot Chat: bug başına yeni thread — eski bağlam premium istek yer.",
        "adv_copilot_tool": "Copilot: “{tool}” ağır — sonraki istekte tek dosya referansı ver.",
        "adv_gemini_crit": "Gemini: bağlamı kısalt; tüm repo değil, bir dosya + hata günlüğü.",
        "adv_gemini_warn": "Gemini: yapıştırma yerine CLI/dosya yolu; sohbeti işe kilitle.",
        "adv_gemini_ok": "Gemini: net hedef + yol; aynı eki yeniden gönderme.",
        "adv_gemini_mcp_many": "Gemini: {n} araç — bu koşuda kullanılmayanı çıkar.",
        "adv_gemini_mcp_use": "Gemini: gerekince “{name}”i açıkça çağır.",
        "adv_gemini_long_chat": "Gemini: yeni iş = yeni sohbet; uzun geçmiş pahalı.",
        "adv_gemini_tool": "Gemini: “{tool}” döngüsü — soruyu sıkılaştır.",
        "adv_local_crit": "Yerel model: bağlam doldu mu? Context’i küçült / büyük modeli indir; burada kota RAM/zaman.",
        "adv_local_warn": "Yerel: düzenlemede küçük model; büyük modeli zor akıl yürütmeye sakla.",
        "adv_local_ok": "Yerel: kısa prompt + dosya yolu; maliyeti context boyutuyla sen yönetirsin.",
        "adv_local_mcp_many": "Yerel: {n} araç hâlâ prompt şişirir — seti küçük tut.",
        "adv_local_mcp_use": "Yerel: uzun yapıştırma yerine “{name}” kullan.",
        "adv_local_long_chat": "Yerel: cevaplar yavaşlarsa oturumu temizle/yeniden başlat.",
        "adv_local_tool": "Yerel: “{tool}” tekrarı — isteği bir kez toplu yaz.",
        "adv_manus_crit": "Manus: geniş tarayıcı/ajan döngüsünü durdur; koşu başına bir somut hedef.",
        "adv_manus_warn": "Manus: açık sekme/aracı sınırla; yeniden tarama yerine sonucu yeniden kullan.",
        "adv_manus_ok": "Manus: site/görev adı ver; “her şeyi keşfet” deme.",
        "adv_manus_mcp_many": "Manus: {n} bağlayıcı — boştakileri kapat.",
        "adv_manus_mcp_use": "Manus: sonraki aramada “{name}”i tercih et.",
        "adv_manus_long_chat": "Manus: yeni hedef = yeni koşu.",
        "adv_manus_tool": "Manus: “{tool}” yoğun — hedefi daralt.",
        "adv_generic_crit": "Kota kritik — bir kısa istek, bir dosya; reset’i bekle.",
        "adv_generic_warn": "Kota düşük — yapıştırma ve uzun ajan koşularını kes.",
        "adv_generic_ok": "Kısa kal: yol + değişiklik + beklenen sonuç.",
        "adv_generic_mcp_many": "{n} araç bağlı — kullanmadığını kapat.",
        "adv_generic_mcp_use": "Uzun elle arama yerine “{name}”i adıyla çağır.",
        "adv_generic_long_chat": "Sonraki iş için yeni sohbet aç.",
        "adv_generic_tool": "“{tool}” sık — tam yol ver.",
        "tip_paste_p": "Büyük dosyaları sohbete yapıştırma.",
        "tip_paste_f": "Yol ver; ajanın yalnız gereken satırları okumasını iste.",
        "tip_vague_p": "Belirsiz istek uzun arama döngüsü yaratır.",
        "tip_vague_f": "Dosya + hata + beklenen sonucu kısa yaz.",
        "tip_dup_p": "Aynı prompt’u tekrarlamak değişmeyen bağlamı yeniden yükler.",
        "tip_dup_f": "Son mesajdan beri yalnızca farkı yaz.",
        "tip_focus_p": "Çok iş veya baştan yazdırma token yer.",
        "tip_focus_f": "Mesaj başına bir iş; mümkünse tek dosya.",
        "tip_rebuild_p": "Her adımda derleme/deploy kota yer.",
        "tip_rebuild_f": "Önce kodu bitir; derlemeyi sonda bir kez çalıştır.",
        "tip_path_p": "Geniş Read/Grep/Shell döngüleri sık görünüyor.",
        "tip_path_f": "Tam dosya yolunu ver; {tools} tekrarından kaçın.",
        "tip_session_p": "Sohbet oturumu çok uzamış.",
        "tip_session_f": "Yeni iş için yeni sohbet aç; eski bağlam yeniden yüklenmesin.",
        "tip_mcp_p": "“{name}” MCP’n var — adıyla çağır.",
        "tip_mcp_f": "Yaz: {name} MCP ile … (uzun elle aramayı atla).",
        "tip_skill_p": "“{name}” skill’i bu işi kısaltabilir.",
        "tip_skill_f": "Yaz: {name} skill’ini takip et.",
        "tip_baseline_p": "Prompt’ları kısa ve tek amaçlı tut.",
        "tip_baseline_f": "Yol + bir değişiklik + beklenen sonuç. Tam yapıştırma ve “her şeyi yeniden yap” yok.",
        "suggest_paste": "Dosya yolu: `{path}` — ilgili satırları diskten oku, tüm içeriği yapıştırma.",
        "suggest_vague": "Dosya: … — Hata: … — Beklenen: …\n(Bağlam: {snippet})",
        "suggest_nofile": "`{path}` içinde: {snippet}",
        "suggest_rewrite": "Yalnızca `{path}` dosyasında şu değişikliği yap: …",
        "suggest_split": "İlk iş: … (devamını ayrı mesajda göndereceğim.)",
        "suggest_rebuild": "Kodu değiştir; derlemeyi en sonda bir kez çalıştır.",
        "suggest_dup": "Son mesajımdan beri yalnızca şu değişti: …",
        "suggest_helper": "{helper} skill'ini kullan: {snippet}",
        "loading": "Yükleniyor…",
        "stat_chats": "{n} oturum", "stat_tok": "{n} token",
        "stat_tools": "{n} araç", "stat_l_chat": "Oturum", "stat_l_tok": "Token", "stat_l_tools": "Araç",
        "left": "%{n} kaldı",
        "issue_paste_p": "Büyük yapıştırma token yer.",
        "issue_paste_f": "Yol ver, içeriği yapıştırma.",
        "issue_paste_c": "Uzun metin yapıştırınca model tüm içeriği yeniden işler.",
        "issue_vague_p": "İstek belirsiz.",
        "issue_vague_f": "Dosya + hata + beklenen sonuç.",
        "issue_vague_c": "Dosya, hata veya hedef yoksa model yanlış varsayım yapar.",
        "issue_rewrite_p": "Baştan yazdırmak pahalı.",
        "issue_rewrite_f": "Tek dosya veya odaklı değişiklik iste.",
        "issue_rewrite_c": "Geniş kapsamlı yeniden yazım bir seferde çok dosyayı etkiler.",
        "issue_split_p": "Birden fazla iş.",
        "issue_split_f": "Ayrı promptlara böl.",
        "issue_split_c": "Aynı mesajda birden fazla görev bağlamı karıştırır.",
        "issue_nofile_p": "Dosya yolu yok.",
        "issue_nofile_f": "Dosyayı veya klasörü adını yaz.",
        "issue_nofile_c": "Dosya adı verilmeden kod sorusu kör aramaya iter.",
        "issue_rebuild_p": "Her adımda exe.",
        "issue_rebuild_f": "Bitince bir kez derle.",
        "issue_rebuild_c": "Her küçük adımda derleme yavaş döngü ekler.",
        "issue_dup_p": "Aynı prompt.",
        "issue_dup_f": "Sadece farkı yaz.",
        "issue_dup_c": "Aynı mesajın tekrarı değişmeyen bağlamı yeniden yükler.",
        "issue_helper_p": "Yardımcı var.",
        "issue_helper_f": "Adını söyle: {helpers}",
        "issue_helper_c": "Uygun skill/MCP varken genel prompt yazılmış.",
        "theme_night": "Gece", "theme_frost": "Buz",
        "theme_aurora": "Aurora", "theme_ember": "Kor", "interval_5": "Canlı",
        "interval_30": "30 sn", "interval_60": "1 dk",
        "interval_300": "5 dk",
    }),
    "en": _finish({
        "title": "Token Tracker", "hello": "Welcome, {name}", "version": "v{v}", "version_long": "Version {v}",
        "error": "error", "empty": "No AI found", "no_data": "No data", "refresh": "Refresh", "close": "Close",
        "hide_tray": "Minimize to tray", "ideas": "Ideas", "tips_nav": "Agent tips",
        "agents_nav": "Agents", "github_nav": "GitHub",
        "usage": "Quota", "settings": "Settings", "lang_label": "Language", "theme_label": "Theme",
        "interval_label": "Refresh interval", "pin_label": "Stay on top",
        "pin_hint": "Keep the window above others", "boot_label": "Open at startup",
        "boot_hint": "Shows in OS startup apps (Windows, macOS, Linux)",
        "quota_label": "Quota access",
        "quota_hint": "Reads local sessions and asks only that service’s official quota API. Tokens are not stored or sent to the developer.",
        "chat_label": "Chat analysis for Ideas",
        "chat_hint": "Scans known local chat folders on this PC only. Nothing is uploaded. Documents and whole disks are not scanned.",
        "consent_title": "Before you start",
        "consent_body": (
            "Token Tracker needs your permission to read local session and chat data on this PC.\n\n"
            "Quota: reads Cursor, Codex, Claude, Gemini, and GitHub Copilot session data and asks only "
            "each service’s official quota API. Tokens are not sent to the developer and are not stored.\n\n"
            "Ideas: scans known local chat folders on this PC only. Nothing is uploaded.\n\n"
            "You can turn these off later in Settings."
        ),
        "consent_enable": "Accept and enable",
        "consent_later": "Keep disabled for now",
        "license_title": "Before you start",
        "license_body": (
            "Before using Token Tracker, review and accept the Software License Agreement and allow "
            "local quota access and chat analysis.\n\n"
            "Quota: reads local session data and asks only each service’s official quota API. "
            "Tokens are not sent to the developer and are not stored.\n\n"
            "Ideas: scans known local chat folders on this PC only. Nothing is uploaded.\n\n"
            "You can turn these off later in Settings."
        ),
        "license_view": "View license text",
        "license_accept": "Accept and continue",
        "license_reject": "I do not accept — exit",
        "license_missing": "License text was not found, so the application cannot start.",
        "usage_need_quota": "Quota access is off. Enable it in Settings.",
        "ideas_need_chat": "Chat analysis is off. You can enable it in Settings.",
        "usage_summary": "{crit} critical · {ok} ok",
        "usage_order_hint": "Critical cards rise automatically. Drag to reorder (gap follows the pointer) · right-click to hide · tap for details.",
        "usage_order_up": "Move up",
        "usage_order_down": "Move down",
        "usage_crit_first": "Critical first",
        "usage_hide": "Hide",
        "usage_hide_menu": "Hide from list",
        "usage_unhide": "restore",
        "usage_hidden_hint": "{n} hidden — tap a name to restore",
        "usage_checked": "checked {t}",
        "tray_lowest": "{name}: {n}% left",
        "warn_label": "Warn below",
        "crit_label": "Critical below",
        "pct_decimals_label": "Percent decimals (X.YYYY)",
        "left_short": "{n}%",
        "model_label": "Model: {name}",
        "tokens_used": "Used: {used} tokens",
        "tokens_used_turn": "Used: {used} tokens · last turn {last}",
        "spend_used": "Spent: {used} · included {limit}",
        "spend_only": "Spent: {used}",
        "usage_drop": " (-{n})",
        "live_tip_on": "Live refresh on",
        "live_tip_busy": "Updating…",
        "live_tip_idle": "Waiting for next refresh",
        "live_tip_err": "Update failed",
        "show": "Show", "quit": "Quit",
        "tray_hide": "In tray. Click to show.", "ideas_wait": "Reading", "ideas_none": "No items",
        "ideas_prompt": "Weak prompt", "ideas_fix": "Better", "ideas_all": "All", "ideas_warn": "Warning",
        "ideas_info": "Info", "ideas_danger": "Critical", "ideas_look": "Inspect",
        "ideas_copied": "Copied", "ideas_opened": "File opened",
        "ideas_detail_title": "Review", "ideas_detail_back": "Back",
        "ideas_detail_problem": "Problem", "ideas_detail_cause": "Why it happens",
        "ideas_detail_solution": "Solution", "ideas_detail_example": "Example from your chat",
        "ideas_detail_info_cause": "Detected from local chat analysis.",
        "ideas_detail_info_solution": "No action needed; this is informational.",
        "ideas_detail_suggest": "Suggested prompt", "ideas_detail_copy": "Copy",
        "ideas_count": "{n}×",
        "ideas_clear": "No notable issues. Scanned {chats} sessions, ~{tokens} tokens.",
        "ideas_filter_empty": "No items match this filter.",
        "tips_title": "Token tips for this agent",
        "tips_hint": "Personal advice from remaining quota, plan, tools and habits.",
        "tips_card_title": "Token tip",
        "tips_card_source": "Saving tip",
        "tips_findings_title": "From your chats",
        "tips_detail_cause": "These habits cut repeated context and tool loops — the main token burn.",
        "tip_paste_p": "Stop pasting large files into chat.",
        "tip_paste_f": "Give a path; ask the agent to read only the needed lines.",
        "tip_vague_p": "Vague asks force long search loops.",
        "tip_vague_f": "Name file + error + expected result in one short message.",
        "tip_dup_p": "Repeating the same prompt reloads unchanged context.",
        "tip_dup_f": "Send only what changed since the last message.",
        "tip_focus_p": "Multi-job or rewrite-all prompts waste tokens.",
        "tip_focus_f": "One task per message; one file when possible.",
        "tip_rebuild_p": "Build/deploy on every step burns quota.",
        "tip_rebuild_f": "Change the code first; build once when finished.",
        "tip_path_p": "Broad Read/Grep/Shell loops showed up often.",
        "tip_path_f": "Point to the exact file; avoid repeating {tools}.",
        "tip_session_p": "A chat session grew very long.",
        "tip_session_f": "Start a fresh chat for a new task so old context is not reloaded.",
        "tip_mcp_p": "MCP “{name}” is available — call it by name.",
        "tip_mcp_f": "Write: use {name} MCP for … (skip a long manual search).",
        "tip_skill_p": "Skill “{name}” can short-circuit this work.",
        "tip_skill_f": "Write: follow the {name} skill.",
        "tip_baseline_p": "Keep prompts short and single-purpose.",
        "tip_baseline_f": "Path + one change + expected result. No full pastes, no “redo everything”.",
        "suggest_paste": "File path: `{path}` — read from disk; do not paste the full content.",
        "suggest_vague": "File: … — Error: … — Expected: …\n(Context: {snippet})",
        "suggest_nofile": "In `{path}`: {snippet}",
        "suggest_rewrite": "Change only `{path}`: one focused edit.",
        "suggest_split": "First task: … (rest in a separate message.)",
        "suggest_rebuild": "Apply the change; build once at the end.",
        "suggest_dup": "Since last message, only this changed: …",
        "suggest_helper": "Use {helper} skill: {snippet}",
        "loading": "Loading…",
        "stat_chats": "{n} sessions", "stat_tok": "{n} tokens",
        "stat_tools": "{n} tools", "stat_l_chat": "Sessions", "stat_l_tok": "Tokens", "stat_l_tools": "Tools",
        "left": "{n}% left",
        "issue_paste_p": "Huge paste burns tokens.", "issue_paste_f": "Give a path.",
        "issue_vague_p": "Ask is vague.", "issue_vague_f": "File + bug + expected.",
        "issue_rewrite_p": "Rewrite-all is costly.", "issue_rewrite_f": "One file.",
        "issue_split_p": "Several jobs.", "issue_split_f": "Split.", "issue_nofile_p": "No file path.",
        "issue_nofile_f": "Name the file.", "issue_rebuild_p": "Exe every step.",
        "issue_rebuild_f": "Build once at the end.", "issue_dup_p": "Same prompt.",
        "issue_dup_f": "Send the delta.", "issue_helper_p": "A helper exists.",
        "issue_helper_f": "Name it: {helpers}", "theme_night": "Night", "theme_frost": "Frost",
        "theme_aurora": "Aurora", "theme_ember": "Ember", "interval_5": "Live",
        "interval_30": "30s", "interval_60": "1 min",
        "interval_300": "5 min",
    }),
}
for code, pack in PACKS.items():
    TEXTS[code] = _finish(pack)
for code in TEXTS:
    TEXTS[code].update(METER.get(code, METER["en"]))
