# generated — 19 dil paketi
PACKS = {
    "es": {
        "hello": 'Bienvenido, {name}',
        "empty": 'No hay IA instalada',
        "no_data": 'Sin datos',
        "refresh": 'Actualizar',
        "close": 'Cerrar',
        "hide_tray": 'Minimizar a bandeja',
        "ideas": 'Ideas',
        "usage": 'Cuota',
        "settings": 'Ajustes',
        "chat": 'Chat',
        "send": 'Enviar',
        "stop": 'Detener',
        "lang_label": 'Idioma',
        "theme_label": 'Tema',
        "interval_label": 'Intervalo de actualizacion',
        "pin_label": 'Siempre visible',
        "pin_hint": 'Mantener la ventana encima',
        "boot_label": 'Abrir al iniciar',
        "boot_hint": 'Iniciar con Windows',
        "show": 'Mostrar',
        "quit": 'Salir',
        "tray_hide": 'En bandeja. Clic para mostrar.',
        "ideas_wait": 'Leyendo',
        "ideas_none": 'Sin registros',
        "ideas_prompt": 'Prompt debil',
        "ideas_fix": 'Mejor',
        "ideas_all": 'Todo',
        "ideas_warn": 'Aviso',
        "ideas_info": 'Info',
        "ideas_look": 'Ver',
        "stat_chats": '{n} chats',
        "stat_tok": '{n} tokens',
        "stat_tools": '{n} herramientas',
        "stat_l_chat": 'Chats',
        "stat_l_tok": 'Tokens',
        "stat_l_tools": 'Herramientas',
        "left": '{n:.0f}% restante',
        "chat_empty": 'Inicia una conversacion',
        "chat_empty_sub": 'Escribe un mensaje para empezar.',
        "chat_ph": 'Escribe tu mensaje...',
        "target_auto": 'Auto',
        "issue_paste_p": 'Pegar mucho gasta tokens.',
        "issue_paste_f": 'Da una ruta.',
        "issue_vague_p": 'Peticion vaga.',
        "issue_vague_f": 'Archivo + error + resultado esperado.',
        "issue_rewrite_p": 'Reescribir todo cuesta.',
        "issue_rewrite_f": 'Un archivo.',
        "issue_split_p": 'Varias tareas.',
        "issue_split_f": 'Separa.',
        "issue_nofile_p": 'Sin ruta de archivo.',
        "issue_nofile_f": 'Nombra el archivo.',
        "issue_rebuild_p": 'Exe en cada paso.',
        "issue_rebuild_f": 'Compila una vez al final.',
        "issue_dup_p": 'Mismo prompt.',
        "issue_dup_f": 'Envia solo el cambio.',
        "issue_helper_p": 'Hay un helper.',
        "issue_helper_f": 'Nombralo.',
        "theme_night": 'Noche',
        "theme_frost": 'Hielo',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Brasa',
        "interval_30": '30 s',
        "interval_60": '1 min',
        "interval_300": '5 min',
        "version_long": 'Version {v}',
    },
    "pt": {
        "hello": 'Bem-vindo, {name}',
        "empty": 'Nenhuma IA instalada',
        "no_data": 'Sem dados',
        "refresh": 'Atualizar',
        "close": 'Fechar',
        "hide_tray": 'Minimizar para bandeja',
        "ideas": 'Ideias',
        "usage": 'Cota',
        "settings": 'Configuracoes',
        "chat": 'Chat',
        "send": 'Enviar',
        "stop": 'Parar',
        "lang_label": 'Idioma',
        "theme_label": 'Tema',
        "interval_label": 'Intervalo de atualizacao',
        "pin_label": 'Sempre visivel',
        "pin_hint": 'Manter janela acima',
        "boot_label": 'Abrir ao iniciar',
        "boot_hint": 'Iniciar com Windows',
        "show": 'Mostrar',
        "quit": 'Sair',
        "tray_hide": 'Na bandeja. Clique para mostrar.',
        "ideas_wait": 'Lendo',
        "ideas_none": 'Sem itens',
        "ideas_prompt": 'Prompt fraco',
        "ideas_fix": 'Melhor',
        "ideas_all": 'Todos',
        "ideas_warn": 'Aviso',
        "ideas_info": 'Info',
        "ideas_look": 'Ver',
        "stat_chats": '{n} chats',
        "stat_tok": '{n} tokens',
        "stat_tools": '{n} ferramentas',
        "stat_l_chat": 'Chats',
        "stat_l_tok": 'Tokens',
        "stat_l_tools": 'Ferramentas',
        "left": '{n:.0f}% restante',
        "chat_empty": 'Inicie uma conversa',
        "chat_empty_sub": 'Digite uma mensagem.',
        "chat_ph": 'Escreva sua mensagem...',
        "target_auto": 'Auto',
        "issue_paste_p": 'Colar muito gasta tokens.',
        "issue_paste_f": 'Informe um caminho.',
        "issue_vague_p": 'Pedido vago.',
        "issue_vague_f": 'Arquivo + erro + esperado.',
        "issue_rewrite_p": 'Reescrever tudo e caro.',
        "issue_rewrite_f": 'Um arquivo.',
        "issue_split_p": 'Varias tarefas.',
        "issue_split_f": 'Separe.',
        "issue_nofile_p": 'Sem caminho.',
        "issue_nofile_f": 'Nomeie o arquivo.',
        "issue_rebuild_p": 'Exe a cada passo.',
        "issue_rebuild_f": 'Compile no final.',
        "issue_dup_p": 'Mesmo prompt.',
        "issue_dup_f": 'Envie so a diferenca.',
        "issue_helper_p": 'Existe helper.',
        "issue_helper_f": 'Diga o nome.',
        "theme_night": 'Noite',
        "theme_frost": 'Gelo',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Brasa',
        "interval_30": '30 s',
        "interval_60": '1 min',
        "interval_300": '5 min',
        "version_long": 'Versao {v}',
    },
    "ar": {
        "hello": 'مرحباً، {name}',
        "empty": 'لا يوجد ذكاء اصطناعي',
        "no_data": 'لا بيانات',
        "refresh": 'تحديث',
        "close": 'إغلاق',
        "hide_tray": 'تصغير إلى الشريط',
        "ideas": 'اقتراحات',
        "usage": 'الحصة',
        "settings": 'الإعدادات',
        "chat": 'دردشة',
        "send": 'إرسال',
        "stop": 'إيقاف',
        "lang_label": 'اللغة',
        "theme_label": 'السمة',
        "interval_label": 'فترة التحديث',
        "pin_label": 'في المقدمة',
        "pin_hint": 'إبقاء النافذة فوق البقية',
        "boot_label": 'فتح عند البدء',
        "boot_hint": 'البدء مع Windows',
        "show": 'إظهار',
        "quit": 'خروج',
        "tray_hide": 'في الشريط. انقر للإظهار.',
        "ideas_wait": 'جارٍ القراءة',
        "ideas_none": 'لا سجلات',
        "ideas_prompt": 'طلب ضعيف',
        "ideas_fix": 'أفضل',
        "ideas_all": 'الكل',
        "ideas_warn": 'تحذير',
        "ideas_info": 'معلومة',
        "ideas_look": 'فحص',
        "stat_chats": '{n} محادثات',
        "stat_tok": '{n} رمز',
        "stat_tools": '{n} أدوات',
        "stat_l_chat": 'محادثات',
        "stat_l_tok": 'رموز',
        "stat_l_tools": 'أدوات',
        "left": '{n:.0f}% متبقي',
        "chat_empty": 'ابدأ محادثة',
        "chat_empty_sub": 'اكتب رسالة للبدء.',
        "chat_ph": 'اكتب رسالتك...',
        "target_auto": 'تلقائي',
        "issue_paste_p": 'لصق كبير يستهلك الرموز.',
        "issue_paste_f": 'أعط مساراً.',
        "issue_vague_p": 'الطلب غير واضح.',
        "issue_vague_f": 'ملف + خطأ + النتيجة.',
        "issue_rewrite_p": 'إعادة الكتابة مكلفة.',
        "issue_rewrite_f": 'ملف واحد.',
        "issue_split_p": 'مهام متعددة.',
        "issue_split_f": 'قسّم.',
        "issue_nofile_p": 'لا مسار ملف.',
        "issue_nofile_f": 'اذكر الملف.',
        "issue_rebuild_p": 'exe في كل خطوة.',
        "issue_rebuild_f": 'ابنِ مرة في النهاية.',
        "issue_dup_p": 'نفس الطلب.',
        "issue_dup_f": 'أرسل الفرق فقط.',
        "issue_helper_p": 'يوجد مساعد.',
        "issue_helper_f": 'اذكر اسمه.',
        "theme_night": 'ليل',
        "theme_frost": 'جليد',
        "theme_aurora": 'شفق',
        "theme_ember": 'جمر',
        "interval_30": '30 ث',
        "interval_60": '1 د',
        "interval_300": '5 د',
        "version_long": 'الإصدار {v}',
    },
    "fa": {
        "hello": 'خوش آمدید، {name}',
        "empty": 'هوش مصنوعی نصب نیست',
        "no_data": 'داده\u200cای نیست',
        "refresh": 'بروزرسانی',
        "close": 'بستن',
        "hide_tray": 'کوچک\u200cکردن به سینی',
        "ideas": 'پیشنهادها',
        "usage": 'سهمیه',
        "settings": 'تنظیمات',
        "chat": 'گفتگو',
        "send": 'ارسال',
        "stop": 'توقف',
        "lang_label": 'زبان',
        "theme_label": 'پوسته',
        "interval_label": 'فاصله بروزرسانی',
        "pin_label": 'همیشه روی',
        "pin_hint": 'پنجره را بالای بقیه نگه دار',
        "boot_label": 'باز شدن با شروع',
        "boot_hint": 'اجرای همراه ویندوز',
        "show": 'نمایش',
        "quit": 'خروج',
        "tray_hide": 'در سینی. برای نمایش کلیک کنید.',
        "ideas_wait": 'در حال خواندن',
        "ideas_none": 'موردی نیست',
        "ideas_prompt": 'درخواست ضعیف',
        "ideas_fix": 'بهتر',
        "ideas_all": 'همه',
        "ideas_warn": 'هشدار',
        "ideas_info": 'اطلاع',
        "ideas_look": 'بررسی',
        "stat_chats": '{n} گفتگو',
        "stat_tok": '{n} توکن',
        "stat_tools": '{n} ابزار',
        "stat_l_chat": 'گفتگو',
        "stat_l_tok": 'توکن',
        "stat_l_tools": 'ابزار',
        "left": '{n:.0f}% باقی',
        "chat_empty": 'گفتگو را شروع کنید',
        "chat_empty_sub": 'پیام بنویسید.',
        "chat_ph": 'پیام خود را بنویسید...',
        "target_auto": 'خودکار',
        "issue_paste_p": 'چسباندن زیاد توکن می\u200cسوزاند.',
        "issue_paste_f": 'مسیر بدهید.',
        "issue_vague_p": 'درخواست مبهم.',
        "issue_vague_f": 'فایل + خطا + نتیجه.',
        "issue_rewrite_p": 'بازنویسی همه گران است.',
        "issue_rewrite_f": 'یک فایل.',
        "issue_split_p": 'چند کار.',
        "issue_split_f": 'جدا کنید.',
        "issue_nofile_p": 'مسیر فایل نیست.',
        "issue_nofile_f": 'فایل را بنویسید.',
        "issue_rebuild_p": 'exe در هر مرحله.',
        "issue_rebuild_f": 'یک بار در پایان بسازید.',
        "issue_dup_p": 'همان درخواست.',
        "issue_dup_f": 'فقط تفاوت را بفرستید.',
        "issue_helper_p": 'کمکی هست.',
        "issue_helper_f": 'نامش را بگویید.',
        "theme_night": 'شب',
        "theme_frost": 'یخ',
        "theme_aurora": 'شفق',
        "theme_ember": 'جمره',
        "interval_30": '30 ث',
        "interval_60": '1 د',
        "interval_300": '5 د',
        "version_long": 'نسخه {v}',
    },
    "hi": {
        "hello": 'स्वागत है, {name}',
        "empty": 'कोई AI नहीं',
        "no_data": 'कोई डेटा नहीं',
        "refresh": 'रीफ़्रेश',
        "close": 'बंद',
        "hide_tray": 'ट्रे में छोटा',
        "ideas": 'सुझाव',
        "usage": 'कोटा',
        "settings": 'सेटिंग्स',
        "chat": 'चैट',
        "send": 'भेजें',
        "stop": 'रोकें',
        "lang_label": 'भाषा',
        "theme_label": 'थीम',
        "interval_label": 'रीफ़्रेश अंतराल',
        "pin_label": 'ऊपर रखें',
        "pin_hint": 'विंडो को ऊपर रखें',
        "boot_label": 'शुरू पर खोलें',
        "boot_hint": 'Windows के साथ शुरू',
        "show": 'दिखाएँ',
        "quit": 'बंद करें',
        "tray_hide": 'ट्रे में। दिखाने के लिए क्लिक।',
        "ideas_wait": 'पढ़ रहा है',
        "ideas_none": 'कोई आइटम नहीं',
        "ideas_prompt": 'कमज़ोर प्रॉम्प्ट',
        "ideas_fix": 'बेहतर',
        "ideas_all": 'सभी',
        "ideas_warn": 'चेतावनी',
        "ideas_info": 'जानकारी',
        "ideas_look": 'देखें',
        "stat_chats": '{n} चैट',
        "stat_tok": '{n} टोकन',
        "stat_tools": '{n} उपकरण',
        "stat_l_chat": 'चैट',
        "stat_l_tok": 'टोकन',
        "stat_l_tools": 'उपकरण',
        "left": '{n:.0f}% बचा',
        "chat_empty": 'बातचीत शुरू करें',
        "chat_empty_sub": 'शुरू करने के लिए लिखें।',
        "chat_ph": 'अपना संदेश लिखें...',
        "target_auto": 'ऑटो',
        "issue_paste_p": 'बड़ा पेस्ट टोकन खाता है।',
        "issue_paste_f": 'पथ दें।',
        "issue_vague_p": 'अनुरोध अस्पष्ट।',
        "issue_vague_f": 'फ़ाइल + बग + अपेक्षित।',
        "issue_rewrite_p": 'सब फिर से लिखना महँगा।',
        "issue_rewrite_f": 'एक फ़ाइल।',
        "issue_split_p": 'कई काम।',
        "issue_split_f": 'अलग करें।',
        "issue_nofile_p": 'फ़ाइल पथ नहीं।',
        "issue_nofile_f": 'फ़ाइल लिखें।',
        "issue_rebuild_p": 'हर चरण exe।',
        "issue_rebuild_f": 'अंत में एक बार बिल्ड।',
        "issue_dup_p": 'वही प्रॉम्प्ट।',
        "issue_dup_f": 'केवल बदलाव भेजें।',
        "issue_helper_p": 'हेल्पर है।',
        "issue_helper_f": 'नाम बताएँ: {helpers}',
        "theme_night": 'रात',
        "theme_frost": 'बर्फ',
        "theme_aurora": 'अरोरा',
        "theme_ember": 'अंगार',
        "interval_30": '30 से',
        "interval_60": '1 मि',
        "interval_300": '5 मि',
        "version_long": 'संस्करण {v}',
    },
    "bn": {
        "hello": 'স্বাগতম, {name}',
        "empty": 'কোনো AI নেই',
        "no_data": 'কোনো ডেটা নেই',
        "refresh": 'রিফ্রেশ',
        "close": 'বন্ধ',
        "hide_tray": 'ট্রে-তে ছোট',
        "ideas": 'পরামর্শ',
        "usage": 'কোটা',
        "settings": 'সেটিংস',
        "chat": 'চ্যাট',
        "send": 'পাঠান',
        "stop": 'থামুন',
        "lang_label": 'ভাষা',
        "theme_label": 'থিম',
        "interval_label": 'রিফ্রেশ间隔',
        "pin_label": 'উপরে রাখুন',
        "pin_hint": 'উইন্ডো উপরে রাখুন',
        "boot_label": 'শুরুতে খুলুন',
        "boot_hint": 'Windows-এর সাথে',
        "show": 'দেখান',
        "quit": 'প্রস্থান',
        "tray_hide": 'ট্রে-তে। দেখতে ক্লিক।',
        "ideas_wait": 'পড়ছে',
        "ideas_none": 'কিছু নেই',
        "ideas_prompt": 'দুর্বল প্রম্পট',
        "ideas_fix": 'ভালো',
        "ideas_all": 'সব',
        "ideas_warn": 'সতর্ক',
        "ideas_info": 'তথ্য',
        "ideas_look": 'দেখুন',
        "stat_chats": '{n} চ্যাট',
        "stat_tok": '{n} টোকেন',
        "stat_tools": '{n} টুল',
        "stat_l_chat": 'চ্যাট',
        "stat_l_tok": 'টোকেন',
        "stat_l_tools": 'টুল',
        "left": '{n:.0f}% বাকি',
        "chat_empty": 'কথোপকথন শুরু',
        "chat_empty_sub": 'লিখুন।',
        "chat_ph": 'বার্তা লিখুন...',
        "target_auto": 'অটো',
        "issue_paste_p": 'বড় পেস্ট টোকেন খায়।',
        "issue_paste_f": 'পথ দিন।',
        "issue_vague_p": 'অস্পষ্ট।',
        "issue_vague_f": 'ফাইল + বাগ + প্রত্যাশা।',
        "issue_rewrite_p": 'সব লিখতে ব্যয়।',
        "issue_rewrite_f": 'এক ফাইল।',
        "issue_split_p": 'একাধিক কাজ।',
        "issue_split_f": 'ভাগ করুন।',
        "issue_nofile_p": 'ফাইল পথ নেই।',
        "issue_nofile_f": 'ফাইল লিখুন।',
        "issue_rebuild_p": 'প্রতি ধাপ exe।',
        "issue_rebuild_f": 'শেষে একবার বিল্ড।',
        "issue_dup_p": 'একই প্রম্পট।',
        "issue_dup_f": 'পার্থক্য পাঠান।',
        "issue_helper_p": 'হেল্পার আছে।',
        "issue_helper_f": 'নাম: {helpers}',
        "theme_night": 'রাত',
        "theme_frost": 'বরফ',
        "theme_aurora": 'অরোরা',
        "theme_ember": 'অগ্নি',
        "interval_30": '30 সে',
        "interval_60": '1 মি',
        "interval_300": '5 মি',
        "version_long": 'সংস্করণ {v}',
    },
    "ur": {
        "hello": 'خوش آمدید، {name}',
        "empty": 'کوئی AI نہیں',
        "no_data": 'کوئی ڈیٹا نہیں',
        "refresh": 'ریفریش',
        "close": 'بند',
        "hide_tray": 'ٹری میں چھوٹا',
        "ideas": 'تجاویز',
        "usage": 'کوٹہ',
        "settings": 'ترتیبات',
        "chat": 'چیٹ',
        "send": 'بھیجیں',
        "stop": 'روکیں',
        "lang_label": 'زبان',
        "theme_label": 'تھیم',
        "interval_label": 'ریفریش وقفہ',
        "pin_label": 'اوپر رکھیں',
        "pin_hint": 'ونڈو اوپر رکھیں',
        "boot_label": 'شروع پر کھولیں',
        "boot_hint": 'Windows کے ساتھ',
        "show": 'دکھائیں',
        "quit": 'بند',
        "tray_hide": 'ٹری میں۔ کلک کریں۔',
        "ideas_wait": 'پڑھ رہا ہے',
        "ideas_none": 'کچھ نہیں',
        "ideas_prompt": 'کمزور پرامپٹ',
        "ideas_fix": 'بہتر',
        "ideas_all": 'سب',
        "ideas_warn": 'انتباہ',
        "ideas_info": 'معلومات',
        "ideas_look": 'دیکھیں',
        "stat_chats": '{n} چیٹ',
        "stat_tok": '{n} ٹوکن',
        "stat_tools": '{n} ٹول',
        "stat_l_chat": 'چیٹ',
        "stat_l_tok": 'ٹوکن',
        "stat_l_tools": 'ٹول',
        "left": '{n:.0f}% باقی',
        "chat_empty": 'بات چیت شروع کریں',
        "chat_empty_sub": 'لکھیں۔',
        "chat_ph": 'اپنا پیغام...',
        "target_auto": 'خودکار',
        "issue_paste_p": 'بڑا پیسٹ ٹوکن کھاتا ہے۔',
        "issue_paste_f": 'راستہ دیں۔',
        "issue_vague_p": 'غیر واضح۔',
        "issue_vague_f": 'فائل + خرابی + نتیجہ۔',
        "issue_rewrite_p": 'سب دوبارہ مہنگا۔',
        "issue_rewrite_f": 'ایک فائل۔',
        "issue_split_p": 'کئی کام۔',
        "issue_split_f": 'الگ کریں۔',
        "issue_nofile_p": 'فائل پاتھ نہیں۔',
        "issue_nofile_f": 'فائل لکھیں۔',
        "issue_rebuild_p": 'ہر قدم exe۔',
        "issue_rebuild_f": 'آخر میں ایک بار۔',
        "issue_dup_p": 'وahi پرامپٹ۔',
        "issue_dup_f": 'فرق بھیجیں۔',
        "issue_helper_p": 'ہیلپر ہے۔',
        "issue_helper_f": 'نام: {helpers}',
        "theme_night": 'رات',
        "theme_frost": 'برف',
        "theme_aurora": 'شفق',
        "theme_ember": ' انگار',
        "interval_30": '30 س',
        "interval_60": '1 من',
        "interval_300": '5 من',
        "version_long": 'ورژن {v}',
    },
    "zh": {
        "hello": '欢迎，{name}',
        "empty": '未找到 AI',
        "no_data": '无数据',
        "refresh": '刷新',
        "close": '关闭',
        "hide_tray": '最小化到托盘',
        "ideas": '建议',
        "usage": '配额',
        "settings": '设置',
        "chat": '聊天',
        "send": '发送',
        "stop": '停止',
        "lang_label": '语言',
        "theme_label": '主题',
        "interval_label": '刷新间隔',
        "pin_label": '置顶',
        "pin_hint": '窗口保持在最前',
        "boot_label": '开机启动',
        "boot_hint": '随 Windows 启动',
        "show": '显示',
        "quit": '退出',
        "tray_hide": '在托盘中。点击显示。',
        "ideas_wait": '读取中',
        "ideas_none": '无记录',
        "ideas_prompt": '提示词较弱',
        "ideas_fix": '更好',
        "ideas_all": '全部',
        "ideas_warn": '警告',
        "ideas_info": '信息',
        "ideas_look": '查看',
        "stat_chats": '{n} 次聊天',
        "stat_tok": '{n} 令牌',
        "stat_tools": '{n} 工具',
        "stat_l_chat": '聊天',
        "stat_l_tok": '令牌',
        "stat_l_tools": '工具',
        "left": '剩余 {n:.0f}%',
        "chat_empty": '开始对话',
        "chat_empty_sub": '输入消息开始。',
        "chat_ph": '输入消息...',
        "target_auto": '自动',
        "issue_paste_p": '大段粘贴浪费令牌。',
        "issue_paste_f": '给出路径。',
        "issue_vague_p": '请求不明确。',
        "issue_vague_f": '文件+错误+期望结果。',
        "issue_rewrite_p": '全部重写成本高。',
        "issue_rewrite_f": '单个文件。',
        "issue_split_p": '多个任务。',
        "issue_split_f": '分开。',
        "issue_nofile_p": '无文件路径。',
        "issue_nofile_f": '写明文件。',
        "issue_rebuild_p": '每步 exe。',
        "issue_rebuild_f": '最后编译一次。',
        "issue_dup_p": '相同提示。',
        "issue_dup_f": '只发送差异。',
        "issue_helper_p": '有助手。',
        "issue_helper_f": '名称: {helpers}',
        "theme_night": '夜',
        "theme_frost": '冰',
        "theme_aurora": '极光',
        "theme_ember": '余烬',
        "interval_30": '30秒',
        "interval_60": '1分',
        "interval_300": '5分',
        "version_long": '版本 {v}',
    },
    "ja": {
        "hello": 'ようこそ、{name}',
        "empty": 'AI が見つかりません',
        "no_data": 'データなし',
        "refresh": '更新',
        "close": '閉じる',
        "hide_tray": 'トレイへ最小化',
        "ideas": '提案',
        "usage": 'クォータ',
        "settings": '設定',
        "chat": 'チャット',
        "send": '送信',
        "stop": '停止',
        "lang_label": '言語',
        "theme_label": 'テーマ',
        "interval_label": '更新間隔',
        "pin_label": '常に前面',
        "pin_hint": 'ウィンドウを前面に',
        "boot_label": '起動時に開く',
        "boot_hint": 'Windows と同時起動',
        "show": '表示',
        "quit": '終了',
        "tray_hide": 'トレイにあります。クリックで表示。',
        "ideas_wait": '読み取り中',
        "ideas_none": '項目なし',
        "ideas_prompt": '弱いプロンプト',
        "ideas_fix": '改善',
        "ideas_all": 'すべて',
        "ideas_warn": '警告',
        "ideas_info": '情報',
        "ideas_look": '確認',
        "stat_chats": '{n} チャット',
        "stat_tok": '{n} トークン',
        "stat_tools": '{n} ツール',
        "stat_l_chat": 'チャット',
        "stat_l_tok": 'トークン',
        "stat_l_tools": 'ツール',
        "left": '残り {n:.0f}%',
        "chat_empty": '会話を開始',
        "chat_empty_sub": 'メッセージを入力。',
        "chat_ph": 'メッセージを入力...',
        "target_auto": '自動',
        "issue_paste_p": '大きな貼り付けはトークン消費。',
        "issue_paste_f": 'パスを指定。',
        "issue_vague_p": '要求が曖昧。',
        "issue_vague_f": 'ファイル+不具合+期待結果。',
        "issue_rewrite_p": '全部書き直しは高コスト。',
        "issue_rewrite_f": '1ファイル。',
        "issue_split_p": '複数作業。',
        "issue_split_f": '分割。',
        "issue_nofile_p": 'ファイルパスなし。',
        "issue_nofile_f": 'ファイル名を。',
        "issue_rebuild_p": '毎ステップ exe。',
        "issue_rebuild_f": '最後に1回ビルド。',
        "issue_dup_p": '同じプロンプト。',
        "issue_dup_f": '差分のみ送信。',
        "issue_helper_p": 'ヘルパーあり。',
        "issue_helper_f": '名前: {helpers}',
        "theme_night": '夜',
        "theme_frost": '氷',
        "theme_aurora": 'オーロラ',
        "theme_ember": '余火',
        "interval_30": '30秒',
        "interval_60": '1分',
        "interval_300": '5分',
        "version_long": 'バージョン {v}',
    },
    "ko": {
        "hello": '환영합니다, {name}',
        "empty": 'AI 없음',
        "no_data": '데이터 없음',
        "refresh": '새로고침',
        "close": '닫기',
        "hide_tray": '트레이로 최소화',
        "ideas": '제안',
        "usage": '할당량',
        "settings": '설정',
        "chat": '채팅',
        "send": '보내기',
        "stop": '중지',
        "lang_label": '언어',
        "theme_label": '테마',
        "interval_label": '새로고침 간격',
        "pin_label": '항상 위',
        "pin_hint": '창을 위에 유지',
        "boot_label": '시작 시 열기',
        "boot_hint": 'Windows와 함께 시작',
        "show": '표시',
        "quit": '종료',
        "tray_hide": '트레이에 있음. 클릭하여 표시.',
        "ideas_wait": '읽는 중',
        "ideas_none": '항목 없음',
        "ideas_prompt": '약한 프롬프트',
        "ideas_fix": '개선',
        "ideas_all": '전체',
        "ideas_warn": '경고',
        "ideas_info": '정보',
        "ideas_look": '보기',
        "stat_chats": '{n} 채팅',
        "stat_tok": '{n} 토큰',
        "stat_tools": '{n} 도구',
        "stat_l_chat": '채팅',
        "stat_l_tok": '토큰',
        "stat_l_tools": '도구',
        "left": '{n:.0f}% 남음',
        "chat_empty": '대화 시작',
        "chat_empty_sub": '메시지를 입력하세요.',
        "chat_ph": '메시지 입력...',
        "target_auto": '자동',
        "issue_paste_p": '큰 붙여넣기는 토큰 소모.',
        "issue_paste_f": '경로 제공.',
        "issue_vague_p": '요청이 모호함.',
        "issue_vague_f": '파일+버그+기대 결과.',
        "issue_rewrite_p": '전체 재작성은 비쌈.',
        "issue_rewrite_f": '한 파일.',
        "issue_split_p": '여러 작업.',
        "issue_split_f": '분리.',
        "issue_nofile_p": '파일 경로 없음.',
        "issue_nofile_f": '파일명 작성.',
        "issue_rebuild_p": '매 단계 exe.',
        "issue_rebuild_f": '마지막에 한 번 빌드.',
        "issue_dup_p": '같은 프롬프트.',
        "issue_dup_f": '차이만 전송.',
        "issue_helper_p": '헬퍼 있음.',
        "issue_helper_f": '이름: {helpers}',
        "theme_night": '밤',
        "theme_frost": '얼음',
        "theme_aurora": '오로라',
        "theme_ember": '불씨',
        "interval_30": '30초',
        "interval_60": '1분',
        "interval_300": '5분',
        "version_long": '버전 {v}',
    },
    "vi": {
        "hello": 'Chào {name}',
        "empty": 'Không có AI',
        "no_data": 'Không có dữ liệu',
        "refresh": 'Làm mới',
        "close": 'Đóng',
        "hide_tray": 'Thu nhỏ khay',
        "ideas": 'Gợi ý',
        "usage": 'Hạn mức',
        "settings": 'Cài đặt',
        "chat": 'Trò chuyện',
        "send": 'Gửi',
        "stop": 'Dừng',
        "lang_label": 'Ngôn ngữ',
        "theme_label": 'Giao diện',
        "interval_label": 'Tần suất làm mới',
        "pin_label": 'Luôn trên cùng',
        "pin_hint": 'Giữ cửa sổ trên cùng',
        "boot_label": 'Mở khi khởi động',
        "boot_hint": 'Khởi động cùng Windows',
        "show": 'Hiện',
        "quit": 'Thoát',
        "tray_hide": 'Trong khay. Nhấn để hiện.',
        "ideas_wait": 'Đang đọc',
        "ideas_none": 'Không có mục',
        "ideas_prompt": 'Prompt yếu',
        "ideas_fix": 'Tốt hơn',
        "ideas_all": 'Tất cả',
        "ideas_warn": 'Cảnh báo',
        "ideas_info": 'Thông tin',
        "ideas_look": 'Xem',
        "stat_chats": '{n} trò chuyện',
        "stat_tok": '{n} token',
        "stat_tools": '{n} công cụ',
        "stat_l_chat": 'Trò chuyện',
        "stat_l_tok": 'Token',
        "stat_l_tools": 'Công cụ',
        "left": 'Còn {n:.0f}%',
        "chat_empty": 'Bắt đầu trò chuyện',
        "chat_empty_sub": 'Nhập tin nhắn.',
        "chat_ph": 'Nhập tin nhắn...',
        "target_auto": 'Tự động',
        "issue_paste_p": 'Dán lớn tốn token.',
        "issue_paste_f": 'Cho đường dẫn.',
        "issue_vague_p": 'Yêu cầu mơ hồ.',
        "issue_vague_f": 'Tệp+lỗi+kết quả.',
        "issue_rewrite_p": 'Viết lại tốn kém.',
        "issue_rewrite_f": 'Một tệp.',
        "issue_split_p": 'Nhiều việc.',
        "issue_split_f": 'Tách.',
        "issue_nofile_p": 'Không có đường dẫn.',
        "issue_nofile_f": 'Ghi tên tệp.',
        "issue_rebuild_p": 'Exe mỗi bước.',
        "issue_rebuild_f": 'Build cuối.',
        "issue_dup_p": 'Cùng prompt.',
        "issue_dup_f": 'Chỉ gửi phần khác.',
        "issue_helper_p": 'Có helper.',
        "issue_helper_f": 'Tên: {helpers}',
        "theme_night": 'Đêm',
        "theme_frost": 'Băng',
        "theme_aurora": 'Cực quang',
        "theme_ember": 'Than',
        "interval_30": '30 giây',
        "interval_60": '1 phút',
        "interval_300": '5 phút',
        "version_long": 'Phiên bản {v}',
    },
    "ms": {
        "hello": 'Selamat datang, {name}',
        "empty": 'Tiada AI',
        "no_data": 'Tiada data',
        "refresh": 'Muat semula',
        "close": 'Tutup',
        "hide_tray": 'Kecilkan ke dulang',
        "ideas": 'Cadangan',
        "usage": 'Kuota',
        "settings": 'Tetapan',
        "chat": 'Sembang',
        "send": 'Hantar',
        "stop": 'Henti',
        "lang_label": 'Bahasa',
        "theme_label": 'Tema',
        "interval_label": 'Selang muat semula',
        "pin_label": 'Sentiasa atas',
        "pin_hint": 'Kekalkan tetingkap atas',
        "boot_label": 'Buka semasa mula',
        "boot_hint": 'Mula dengan Windows',
        "show": 'Tunjuk',
        "quit": 'Keluar',
        "tray_hide": 'Dalam dulang. Klik untuk tunjuk.',
        "ideas_wait": 'Membaca',
        "ideas_none": 'Tiada item',
        "ideas_prompt": 'Prompt lemah',
        "ideas_fix": 'Lebih baik',
        "ideas_all": 'Semua',
        "ideas_warn": 'Amaran',
        "ideas_info": 'Info',
        "ideas_look": 'Lihat',
        "stat_chats": '{n} sembang',
        "stat_tok": '{n} token',
        "stat_tools": '{n} alat',
        "stat_l_chat": 'Sembang',
        "stat_l_tok": 'Token',
        "stat_l_tools": 'Alat',
        "left": '{n:.0f}% tinggal',
        "chat_empty": 'Mulakan perbualan',
        "chat_empty_sub": 'Taip mesej.',
        "chat_ph": 'Taip mesej...',
        "target_auto": 'Auto',
        "issue_paste_p": 'Tampal besar habiskan token.',
        "issue_paste_f": 'Berikan laluan.',
        "issue_vague_p": 'Permintaan kabur.',
        "issue_vague_f": 'Fail+bug+jangkaan.',
        "issue_rewrite_p": 'Tulis semula mahal.',
        "issue_rewrite_f": 'Satu fail.',
        "issue_split_p": 'Beberapa kerja.',
        "issue_split_f": 'Asingkan.',
        "issue_nofile_p": 'Tiada laluan fail.',
        "issue_nofile_f": 'Nama fail.',
        "issue_rebuild_p": 'Exe setiap langkah.',
        "issue_rebuild_f": 'Bina sekali akhir.',
        "issue_dup_p": 'Prompt sama.',
        "issue_dup_f": 'Hantar perbezaan.',
        "issue_helper_p": 'Ada helper.',
        "issue_helper_f": 'Nama: {helpers}',
        "theme_night": 'Malam',
        "theme_frost": 'Ais',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Bara',
        "interval_30": '30 saat',
        "interval_60": '1 min',
        "interval_300": '5 min',
        "version_long": 'Versi {v}',
    },
    "sv": {
        "hello": 'Välkommen, {name}',
        "empty": 'Ingen AI hittades',
        "no_data": 'Ingen data',
        "refresh": 'Uppdatera',
        "close": 'Stäng',
        "hide_tray": 'Minimera till fält',
        "ideas": 'Idéer',
        "usage": 'Kvot',
        "settings": 'Inställningar',
        "chat": 'Chatt',
        "send": 'Skicka',
        "stop": 'Stopp',
        "lang_label": 'Språk',
        "theme_label": 'Tema',
        "interval_label": 'Uppdateringsintervall',
        "pin_label": 'Alltid överst',
        "pin_hint": 'Håll fönstret överst',
        "boot_label": 'Öppna vid start',
        "boot_hint": 'Starta med Windows',
        "show": 'Visa',
        "quit": 'Avsluta',
        "tray_hide": 'I fältet. Klicka för att visa.',
        "ideas_wait": 'Läser',
        "ideas_none": 'Inga objekt',
        "ideas_prompt": 'Svag prompt',
        "ideas_fix": 'Bättre',
        "ideas_all": 'Alla',
        "ideas_warn": 'Varning',
        "ideas_info": 'Info',
        "ideas_look": 'Visa',
        "stat_chats": '{n} chattar',
        "stat_tok": '{n} tokens',
        "stat_tools": '{n} verktyg',
        "stat_l_chat": 'Chattar',
        "stat_l_tok": 'Tokens',
        "stat_l_tools": 'Verktyg',
        "left": '{n:.0f}% kvar',
        "chat_empty": 'Starta en konversation',
        "chat_empty_sub": 'Skriv ett meddelande.',
        "chat_ph": 'Skriv ditt meddelande...',
        "target_auto": 'Auto',
        "issue_paste_p": 'Stort klistra förbrukar tokens.',
        "issue_paste_f": 'Ge en sökväg.',
        "issue_vague_p": 'Begäran otydlig.',
        "issue_vague_f": 'Fil+bugg+förväntat.',
        "issue_rewrite_p": 'Skriv om allt är dyrt.',
        "issue_rewrite_f": 'En fil.',
        "issue_split_p": 'Flera jobb.',
        "issue_split_f": 'Dela upp.',
        "issue_nofile_p": 'Ingen filsökväg.',
        "issue_nofile_f": 'Namnge filen.',
        "issue_rebuild_p": 'Exe varje steg.',
        "issue_rebuild_f": 'Bygg en gång i slutet.',
        "issue_dup_p": 'Samma prompt.',
        "issue_dup_f": 'Skicka bara diff.',
        "issue_helper_p": 'Helper finns.',
        "issue_helper_f": 'Namn: {helpers}',
        "theme_night": 'Natt',
        "theme_frost": 'Frost',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Glöd',
        "interval_30": '30 s',
        "interval_60": '1 min',
        "interval_300": '5 min',
        "version_long": 'Version {v}',
    },
    "cs": {
        "hello": 'Vítejte, {name}',
        "empty": 'Žádná AI',
        "no_data": 'Žádná data',
        "refresh": 'Obnovit',
        "close": 'Zavřít',
        "hide_tray": 'Minimalizovat do lišty',
        "ideas": 'Nápady',
        "usage": 'Kvóta',
        "settings": 'Nastavení',
        "chat": 'Chat',
        "send": 'Odeslat',
        "stop": 'Zastavit',
        "lang_label": 'Jazyk',
        "theme_label": 'Motiv',
        "interval_label": 'Interval obnovení',
        "pin_label": 'Vždy navrchu',
        "pin_hint": 'Okno nad ostatními',
        "boot_label": 'Otevřít při startu',
        "boot_hint": 'Spustit s Windows',
        "show": 'Zobrazit',
        "quit": 'Ukončit',
        "tray_hide": 'V liště. Klikněte pro zobrazení.',
        "ideas_wait": 'Čtení',
        "ideas_none": 'Žádné položky',
        "ideas_prompt": 'Slabý prompt',
        "ideas_fix": 'Lépe',
        "ideas_all": 'Vše',
        "ideas_warn": 'Varování',
        "ideas_info": 'Info',
        "ideas_look": 'Zobrazit',
        "stat_chats": '{n} chatů',
        "stat_tok": '{n} tokenů',
        "stat_tools": '{n} nástrojů',
        "stat_l_chat": 'Chaty',
        "stat_l_tok": 'Tokeny',
        "stat_l_tools": 'Nástroje',
        "left": 'Zbývá {n:.0f} %',
        "chat_empty": 'Začněte konverzaci',
        "chat_empty_sub": 'Napište zprávu.',
        "chat_ph": 'Napište zprávu...',
        "target_auto": 'Auto',
        "issue_paste_p": 'Velké vložení spotřebuje tokeny.',
        "issue_paste_f": 'Uveďte cestu.',
        "issue_vague_p": 'Nejasný požadavek.',
        "issue_vague_f": 'Soubor+chyba+očekávání.',
        "issue_rewrite_p": 'Přepsat vše je drahé.',
        "issue_rewrite_f": 'Jeden soubor.',
        "issue_split_p": 'Více úkolů.',
        "issue_split_f": 'Rozdělte.',
        "issue_nofile_p": 'Bez cesty k souboru.',
        "issue_nofile_f": 'Uveďte soubor.',
        "issue_rebuild_p": 'Exe každý krok.',
        "issue_rebuild_f": 'Sestavte jednou na konci.',
        "issue_dup_p": 'Stejný prompt.',
        "issue_dup_f": 'Pošlete jen rozdíl.',
        "issue_helper_p": 'Existuje helper.',
        "issue_helper_f": 'Jméno: {helpers}',
        "theme_night": 'Noc',
        "theme_frost": 'Led',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Žár',
        "interval_30": '30 s',
        "interval_60": '1 min',
        "interval_300": '5 min',
        "version_long": 'Verze {v}',
    },
    "sk": {
        "hello": 'Vitajte, {name}',
        "empty": 'Žiadna AI',
        "no_data": 'Žiadne dáta',
        "refresh": 'Obnoviť',
        "close": 'Zavrieť',
        "hide_tray": 'Minimalizovať do lišty',
        "ideas": 'Nápady',
        "usage": 'Kvóta',
        "settings": 'Nastavenia',
        "chat": 'Chat',
        "send": 'Odoslať',
        "stop": 'Zastaviť',
        "lang_label": 'Jazyk',
        "theme_label": 'Motív',
        "interval_label": 'Interval obnovenia',
        "pin_label": 'Vždy navrchu',
        "pin_hint": 'Okno nad ostatnými',
        "boot_label": 'Otvoriť pri štarte',
        "boot_hint": 'Spustiť s Windows',
        "show": 'Zobraziť',
        "quit": 'Ukončiť',
        "tray_hide": 'V lište. Kliknite pre zobrazenie.',
        "ideas_wait": 'Čítanie',
        "ideas_none": 'Žiadne položky',
        "ideas_prompt": 'Slabý prompt',
        "ideas_fix": 'Lepšie',
        "ideas_all": 'Všetko',
        "ideas_warn": 'Varovanie',
        "ideas_info": 'Info',
        "ideas_look": 'Zobraziť',
        "stat_chats": '{n} chatov',
        "stat_tok": '{n} tokenov',
        "stat_tools": '{n} nástrojov',
        "stat_l_chat": 'Chaty',
        "stat_l_tok": 'Tokeny',
        "stat_l_tools": 'Nástroje',
        "left": 'Zostáva {n:.0f} %',
        "chat_empty": 'Začnite konverzáciu',
        "chat_empty_sub": 'Napíšte správu.',
        "chat_ph": 'Napíšte správu...',
        "target_auto": 'Auto',
        "issue_paste_p": 'Veľké vloženie spotrebuje tokeny.',
        "issue_paste_f": 'Uveďte cestu.',
        "issue_vague_p": 'Nejasná požiadavka.',
        "issue_vague_f": 'Súbor+chyba+očakávanie.',
        "issue_rewrite_p": 'Prepísať všetko je drahé.',
        "issue_rewrite_f": 'Jeden súbor.',
        "issue_split_p": 'Viac úloh.',
        "issue_split_f": 'Rozdeľte.',
        "issue_nofile_p": 'Bez cesty k súboru.',
        "issue_nofile_f": 'Uveďte súbor.',
        "issue_rebuild_p": 'Exe každý krok.',
        "issue_rebuild_f": 'Zostavte raz na konci.',
        "issue_dup_p": 'Rovnaký prompt.',
        "issue_dup_f": 'Pošlite len rozdiel.',
        "issue_helper_p": 'Existuje helper.',
        "issue_helper_f": 'Meno: {helpers}',
        "theme_night": 'Noc',
        "theme_frost": 'Ľad',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Žiar',
        "interval_30": '30 s',
        "interval_60": '1 min',
        "interval_300": '5 min',
        "version_long": 'Verzia {v}',
    },
    "hr": {
        "hello": 'Dobrodošli, {name}',
        "empty": 'Nema AI',
        "no_data": 'Nema podataka',
        "refresh": 'Osvježi',
        "close": 'Zatvori',
        "hide_tray": 'Minimiziraj u ladicu',
        "ideas": 'Ideje',
        "usage": 'Kvota',
        "settings": 'Postavke',
        "chat": 'Razgovor',
        "send": 'Pošalji',
        "stop": 'Zaustavi',
        "lang_label": 'Jezik',
        "theme_label": 'Tema',
        "interval_label": 'Interval osvježavanja',
        "pin_label": 'Uvijek iznad',
        "pin_hint": 'Prozor iznad ostalih',
        "boot_label": 'Otvori pri pokretanju',
        "boot_hint": 'Pokreni s Windowsom',
        "show": 'Prikaži',
        "quit": 'Izlaz',
        "tray_hide": 'U ladici. Klikni za prikaz.',
        "ideas_wait": 'Čitanje',
        "ideas_none": 'Nema stavki',
        "ideas_prompt": 'Slab prompt',
        "ideas_fix": 'Bolje',
        "ideas_all": 'Sve',
        "ideas_warn": 'Upozorenje',
        "ideas_info": 'Info',
        "ideas_look": 'Pogledaj',
        "stat_chats": '{n} razgovora',
        "stat_tok": '{n} tokena',
        "stat_tools": '{n} alata',
        "stat_l_chat": 'Razgovori',
        "stat_l_tok": 'Tokeni',
        "stat_l_tools": 'Alati',
        "left": 'Preostalo {n:.0f} %',
        "chat_empty": 'Započni razgovor',
        "chat_empty_sub": 'Upiši poruku.',
        "chat_ph": 'Upiši poruku...',
        "target_auto": 'Auto',
        "issue_paste_p": 'Veliko lijepljenje troši tokeni.',
        "issue_paste_f": 'Daj put.',
        "issue_vague_p": 'Zahtjev nejasan.',
        "issue_vague_f": 'Datoteka+bug+očekivano.',
        "issue_rewrite_p": 'Prepisivanje skupo.',
        "issue_rewrite_f": 'Jedna datoteka.',
        "issue_split_p": 'Više poslova.',
        "issue_split_f": 'Razdvoji.',
        "issue_nofile_p": 'Nema puta datoteke.',
        "issue_nofile_f": 'Imenuj datoteku.',
        "issue_rebuild_p": 'Exe svaki korak.',
        "issue_rebuild_f": 'Gradi jednom na kraju.',
        "issue_dup_p": 'Isti prompt.',
        "issue_dup_f": 'Pošalji samo razliku.',
        "issue_helper_p": 'Postoji helper.',
        "issue_helper_f": 'Ime: {helpers}',
        "theme_night": 'Noć',
        "theme_frost": 'Led',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Žar',
        "interval_30": '30 s',
        "interval_60": '1 min',
        "interval_300": '5 min',
        "version_long": 'Verzija {v}',
    },
    "sr": {
        "hello": 'Добродошли, {name}',
        "empty": 'Нема AI',
        "no_data": 'Нема података',
        "refresh": 'Освежи',
        "close": 'Затвори',
        "hide_tray": 'У трај',
        "ideas": 'Идеје',
        "usage": 'Квота',
        "settings": 'Подешавања',
        "chat": 'Ћаскање',
        "send": 'Пошаљи',
        "stop": 'Заустави',
        "lang_label": 'Језик',
        "theme_label": 'Тема',
        "interval_label": 'Интервал',
        "pin_label": 'Увек изнад',
        "pin_hint": 'Прозор изнад',
        "boot_label": 'Отвори при покретању',
        "boot_hint": 'Са Windows-ом',
        "show": 'Прикажи',
        "quit": 'Изађи',
        "tray_hide": 'У трају. Кликни.',
        "ideas_wait": 'Читање',
        "ideas_none": 'Нема ставки',
        "ideas_prompt": 'Слаб prompt',
        "ideas_fix": 'Боље',
        "ideas_all": 'Све',
        "ideas_warn": 'Упозорење',
        "ideas_info": 'Info',
        "ideas_look": 'Погледај',
        "stat_chats": '{n} ћаскања',
        "stat_tok": '{n} токена',
        "stat_tools": '{n} алата',
        "stat_l_chat": 'Ћаскања',
        "stat_l_tok": 'Токени',
        "stat_l_tools": 'Алати',
        "left": 'Преостало {n:.0f} %',
        "chat_empty": 'Започни разговор',
        "chat_empty_sub": 'Унеси поруку.',
        "chat_ph": 'Унеси поруку...',
        "target_auto": 'Аутo',
        "issue_paste_p": 'Велико лепљење троши.',
        "issue_paste_f": 'Дaj пут.',
        "issue_vague_p": 'Нејасно.',
        "issue_vague_f": 'Датотека+грешка+очекивано.',
        "issue_rewrite_p": 'Преписивање скупo.',
        "issue_rewrite_f": 'Једна датотека.',
        "issue_split_p": 'Више posлова.',
        "issue_split_f": 'Раздвој.',
        "issue_nofile_p": 'Нема пута.',
        "issue_nofile_f": 'Име датотеке.',
        "issue_rebuild_p": 'Exe svaki korak.',
        "issue_rebuild_f": 'Гради на крају.',
        "issue_dup_p": 'Иsti prompt.',
        "issue_dup_f": 'Pošalji razliku.',
        "issue_helper_p": 'Helper postoji.',
        "issue_helper_f": 'Име: {helpers}',
        "theme_night": 'Ноћ',
        "theme_frost": 'Лед',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Жар',
        "interval_30": '30 s',
        "interval_60": '1 min',
        "interval_300": '5 min',
        "version_long": 'Verzija {v}',
    },
    "az": {
        "hello": 'Xoş gəlmisiniz, {name}',
        "empty": 'AI yoxdur',
        "no_data": 'Məlumat yoxdur',
        "refresh": 'Yenilə',
        "close": 'Bağla',
        "hide_tray": 'Tray-ə kiçilt',
        "ideas": 'Tövsiyələr',
        "usage": 'Kvota',
        "settings": 'Parametrlər',
        "chat": 'Söhbət',
        "send": 'Göndər',
        "stop": 'Dayandır',
        "lang_label": 'Dil',
        "theme_label": 'Tema',
        "interval_label": 'Yeniləmə intervalı',
        "pin_label": 'Həmişə üstdə',
        "pin_hint": 'Pəncərəni üstdə saxla',
        "boot_label": 'Başlanğıcda aç',
        "boot_hint": 'Windows ilə',
        "show": 'Göstər',
        "quit": 'Çıx',
        "tray_hide": 'Tray-də. Klik et.',
        "ideas_wait": 'Oxunur',
        "ideas_none": 'Yoxdur',
        "ideas_prompt": 'Zəif prompt',
        "ideas_fix": 'Daha yaxşı',
        "ideas_all": 'Hamısı',
        "ideas_warn": 'Xəbərdarlıq',
        "ideas_info": 'Məlumat',
        "ideas_look": 'Bax',
        "stat_chats": '{n} söhbət',
        "stat_tok": '{n} token',
        "stat_tools": '{n} alət',
        "stat_l_chat": 'Söhbətlər',
        "stat_l_tok": 'Token',
        "stat_l_tools": 'Alətlər',
        "left": '{n:.0f}% qaldı',
        "chat_empty": 'Söhbət başlat',
        "chat_empty_sub": 'Mesaj yaz.',
        "chat_ph": 'Mesajınızı yazın...',
        "target_auto": 'Avto',
        "issue_paste_p": 'Böyük yapışdırma token yeyir.',
        "issue_paste_f": 'Yol ver.',
        "issue_vague_p": 'Qeyri-müəyyən.',
        "issue_vague_f": 'Fayl+xəta+gözlənilən.',
        "issue_rewrite_p": 'Hamısını yazmaq bahadır.',
        "issue_rewrite_f": 'Bir fayl.',
        "issue_split_p": 'Bir neçə iş.',
        "issue_split_f": 'Ayır.',
        "issue_nofile_p": 'Fayl yolu yoxdur.',
        "issue_nofile_f": 'Fayl adı.',
        "issue_rebuild_p": 'Hər addımda exe.',
        "issue_rebuild_f": 'Sonda bir dəfə.',
        "issue_dup_p": 'Eyni prompt.',
        "issue_dup_f": 'Fərqi göndər.',
        "issue_helper_p": 'Helper var.',
        "issue_helper_f": 'Ad: {helpers}',
        "theme_night": 'Gecə',
        "theme_frost": 'Buz',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Közlə',
        "interval_30": '30 san',
        "interval_60": '1 dəq',
        "interval_300": '5 dəq',
        "version_long": 'Versiya {v}',
    },
    "sw": {
        "hello": 'Karibu, {name}',
        "empty": 'Hakuna AI',
        "no_data": 'Hakuna data',
        "refresh": 'Onyesha upya',
        "close": 'Funga',
        "hide_tray": 'Punguza kwenye tray',
        "ideas": 'Mapendekezo',
        "usage": 'Kiasi',
        "settings": 'Mipangilio',
        "chat": 'Soga',
        "send": 'Tuma',
        "stop": 'Simama',
        "lang_label": 'Lugha',
        "theme_label": 'Mandhari',
        "interval_label": 'Muda wa kuonyesha upya',
        "pin_label": 'Daima juu',
        "pin_hint": 'Weka dirisha juu',
        "boot_label": 'Fungua wakati wa kuanza',
        "boot_hint": 'Anza na Windows',
        "show": 'Onyesha',
        "quit": 'Toka',
        "tray_hide": 'Kwenye tray. Bofya kuonyesha.',
        "ideas_wait": 'Inasoma',
        "ideas_none": 'Hakuna vitu',
        "ideas_prompt": 'Prompt dhaifu',
        "ideas_fix": 'Bora',
        "ideas_all": 'Zote',
        "ideas_warn": 'Onyo',
        "ideas_info": 'Taarifa',
        "ideas_look": 'Angalia',
        "stat_chats": '{n} mazungumzo',
        "stat_tok": '{n} tokeni',
        "stat_tools": '{n} zana',
        "stat_l_chat": 'Mazungumzo',
        "stat_l_tok": 'Tokeni',
        "stat_l_tools": 'Zana',
        "left": '{n:.0f}% imesalia',
        "chat_empty": 'Anza mazungumzo',
        "chat_empty_sub": 'Andika ujumbe.',
        "chat_ph": 'Andika ujumbe...',
        "target_auto": 'Otomatiki',
        "issue_paste_p": 'Bandika kubwa hutumia tokeni.',
        "issue_paste_f": 'Toa njia.',
        "issue_vague_p": 'Ombi halijulikani.',
        "issue_vague_f": 'Faili+hitilafu+matarajio.',
        "issue_rewrite_p": 'Kuandika upya ni ghali.',
        "issue_rewrite_f": 'Faili moja.',
        "issue_split_p": 'Kazi nyingi.',
        "issue_split_f": 'Gawanya.',
        "issue_nofile_p": 'Hakuna njia ya faili.',
        "issue_nofile_f": 'Andika faili.',
        "issue_rebuild_p": 'Exe kila hatua.',
        "issue_rebuild_f": 'Jenga mara moja mwishoni.',
        "issue_dup_p": 'Prompt sawa.',
        "issue_dup_f": 'Tuma tofauti tu.',
        "issue_helper_p": 'Kuna msaidizi.',
        "issue_helper_f": 'Jina: {helpers}',
        "theme_night": 'Usiku',
        "theme_frost": 'Barafu',
        "theme_aurora": 'Aurora',
        "theme_ember": 'Makaa',
        "interval_30": 'sek 30',
        "interval_60": 'dak 1',
        "interval_300": 'dak 5',
        "version_long": 'Toleo {v}',
    },
}

CHAT_TIPS = {'es': {'paste': 'Da una ruta.', 'vague': 'Archivo + error + resultado esperado.', 'rewrite': 'Un archivo.', 'split': 'Separa.', 'nofile': 'Nombra el archivo.', 'rebuild': 'Compila una vez al final.', 'dup': 'Envia solo el cambio.', 'helper': 'Nombralo. {helpers}'}, 'pt': {'paste': 'Informe um caminho.', 'vague': 'Arquivo + erro + esperado.', 'rewrite': 'Um arquivo.', 'split': 'Separe.', 'nofile': 'Nomeie o arquivo.', 'rebuild': 'Compile no final.', 'dup': 'Envie so a diferenca.', 'helper': 'Diga o nome. {helpers}'}, 'ar': {'paste': 'أعط مساراً.', 'vague': 'ملف + خطأ + النتيجة.', 'rewrite': 'ملف واحد.', 'split': 'قسّم.', 'nofile': 'اذكر الملف.', 'rebuild': 'ابنِ مرة في النهاية.', 'dup': 'أرسل الفرق فقط.', 'helper': 'اذكر اسمه. {helpers}'}, 'fa': {'paste': 'مسیر بدهید.', 'vague': 'فایل + خطا + نتیجه.', 'rewrite': 'یک فایل.', 'split': 'جدا کنید.', 'nofile': 'فایل را بنویسید.', 'rebuild': 'یک بار در پایان بسازید.', 'dup': 'فقط تفاوت را بفرستید.', 'helper': 'نامش را بگویید. {helpers}'}, 'hi': {'paste': 'पथ दें।', 'vague': 'फ़ाइल + बग + अपेक्षित।', 'rewrite': 'एक फ़ाइल।', 'split': 'अलग करें।', 'nofile': 'फ़ाइल लिखें।', 'rebuild': 'अंत में एक बार बिल्ड।', 'dup': 'केवल बदलाव भेजें।', 'helper': 'नाम बताएँ: {helpers}'}, 'bn': {'paste': 'পথ দিন।', 'vague': 'ফাইল + বাগ + প্রত্যাশা।', 'rewrite': 'এক ফাইল।', 'split': 'ভাগ করুন।', 'nofile': 'ফাইল লিখুন।', 'rebuild': 'শেষে একবার বিল্ড।', 'dup': 'পার্থক্য পাঠান।', 'helper': 'নাম: {helpers}'}, 'ur': {'paste': 'راستہ دیں۔', 'vague': 'فائل + خرابی + نتیجہ۔', 'rewrite': 'ایک فائل۔', 'split': 'الگ کریں۔', 'nofile': 'فائل لکھیں۔', 'rebuild': 'آخر میں ایک بار۔', 'dup': 'فرق بھیجیں۔', 'helper': 'نام: {helpers}'}, 'zh': {'paste': '给出路径。', 'vague': '文件+错误+期望结果。', 'rewrite': '单个文件。', 'split': '分开。', 'nofile': '写明文件。', 'rebuild': '最后编译一次。', 'dup': '只发送差异。', 'helper': '名称: {helpers}'}, 'ja': {'paste': 'パスを指定。', 'vague': 'ファイル+不具合+期待結果。', 'rewrite': '1ファイル。', 'split': '分割。', 'nofile': 'ファイル名を。', 'rebuild': '最後に1回ビルド。', 'dup': '差分のみ送信。', 'helper': '名前: {helpers}'}, 'ko': {'paste': '경로 제공.', 'vague': '파일+버그+기대 결과.', 'rewrite': '한 파일.', 'split': '분리.', 'nofile': '파일명 작성.', 'rebuild': '마지막에 한 번 빌드.', 'dup': '차이만 전송.', 'helper': '이름: {helpers}'}, 'vi': {'paste': 'Cho đường dẫn.', 'vague': 'Tệp+lỗi+kết quả.', 'rewrite': 'Một tệp.', 'split': 'Tách.', 'nofile': 'Ghi tên tệp.', 'rebuild': 'Build cuối.', 'dup': 'Chỉ gửi phần khác.', 'helper': 'Tên: {helpers}'}, 'ms': {'paste': 'Berikan laluan.', 'vague': 'Fail+bug+jangkaan.', 'rewrite': 'Satu fail.', 'split': 'Asingkan.', 'nofile': 'Nama fail.', 'rebuild': 'Bina sekali akhir.', 'dup': 'Hantar perbezaan.', 'helper': 'Nama: {helpers}'}, 'sv': {'paste': 'Ge en sökväg.', 'vague': 'Fil+bugg+förväntat.', 'rewrite': 'En fil.', 'split': 'Dela upp.', 'nofile': 'Namnge filen.', 'rebuild': 'Bygg en gång i slutet.', 'dup': 'Skicka bara diff.', 'helper': 'Namn: {helpers}'}, 'cs': {'paste': 'Uveďte cestu.', 'vague': 'Soubor+chyba+očekávání.', 'rewrite': 'Jeden soubor.', 'split': 'Rozdělte.', 'nofile': 'Uveďte soubor.', 'rebuild': 'Sestavte jednou na konci.', 'dup': 'Pošlete jen rozdíl.', 'helper': 'Jméno: {helpers}'}, 'sk': {'paste': 'Uveďte cestu.', 'vague': 'Súbor+chyba+očakávanie.', 'rewrite': 'Jeden súbor.', 'split': 'Rozdeľte.', 'nofile': 'Uveďte súbor.', 'rebuild': 'Zostavte raz na konci.', 'dup': 'Pošlite len rozdiel.', 'helper': 'Meno: {helpers}'}, 'hr': {'paste': 'Daj put.', 'vague': 'Datoteka+bug+očekivano.', 'rewrite': 'Jedna datoteka.', 'split': 'Razdvoji.', 'nofile': 'Imenuj datoteku.', 'rebuild': 'Gradi jednom na kraju.', 'dup': 'Pošalji samo razliku.', 'helper': 'Ime: {helpers}'}, 'sr': {'paste': 'Дaj пут.', 'vague': 'Датотека+грешка+очекивано.', 'rewrite': 'Једна датотека.', 'split': 'Раздвој.', 'nofile': 'Име датотеке.', 'rebuild': 'Гради на крају.', 'dup': 'Pošalji razliku.', 'helper': 'Име: {helpers}'}, 'az': {'paste': 'Yol ver.', 'vague': 'Fayl+xəta+gözlənilən.', 'rewrite': 'Bir fayl.', 'split': 'Ayır.', 'nofile': 'Fayl adı.', 'rebuild': 'Sonda bir dəfə.', 'dup': 'Fərqi göndər.', 'helper': 'Ad: {helpers}'}, 'sw': {'paste': 'Toa njia.', 'vague': 'Faili+hitilafu+matarajio.', 'rewrite': 'Faili moja.', 'split': 'Gawanya.', 'nofile': 'Andika faili.', 'rebuild': 'Jenga mara moja mwishoni.', 'dup': 'Tuma tofauti tu.', 'helper': 'Jina: {helpers}'}, 'tr': {'paste': 'Dosya yapıştırma; yol ver.', 'vague': 'Dosya + ne bozuk + beklenen sonuç yaz.', 'rewrite': 'Tek dosya / tek fonksiyon iste.', 'split': 'Her işi ayrı gönder.', 'nofile': 'Hedef dosyayı yaz.', 'rebuild': "Exe'yi iş bitince bir kez derle.", 'dup': 'Sadece farkı yaz.', 'helper': 'Kurulu yardımcı: {helpers}'}, 'en': {'paste': "Don't paste files; give a path.", 'vague': "File + what's wrong + expected result.", 'rewrite': 'Ask for one file or function.', 'split': 'One job per message.', 'nofile': 'Name the file.', 'rebuild': 'Build the exe once, at the end.', 'dup': 'Send only the delta.', 'helper': 'Use: {helpers}'}}

CHAT_HEAD = {'tr': 'Doğrusu / düzeltme:', 'en': 'Better ask:', 'es': 'Mejor pregunta:', 'pt': 'Melhor pedido:', 'ar': 'الأفضل:', 'fa': 'بهتر بپرس:', 'hi': 'बेहतर:', 'bn': 'ভালো:', 'ur': 'بہتر:', 'zh': '更好的问法:', 'ja': 'より良い質問:', 'ko': '더 나은 질문:', 'vi': 'Hỏi tốt hơn:', 'ms': 'Tanya lebih baik:', 'sv': 'Bättre fråga:', 'cs': 'Lepší dotaz:', 'sk': 'Lepší dotaz:', 'hr': 'Bolje pitaj:', 'sr': 'Bolje pitaj:', 'az': 'Daha yaxşı:', 'sw': 'Uliza bora:'}

SWITCH_MSG = {'tr': {'ollama_off': 'Ollama kapalı. ollama serve çalıştır.', 'no_session': '{target} bu kutudan oturumunu paylaşmaz. Düzeltilmiş cümleyi oraya yapıştır. Yerel sohbet için Ollama seç.'}, 'en': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'es': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'pt': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'ar': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'fa': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'hi': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'bn': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'ur': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'zh': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'ja': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'ko': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'vi': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'ms': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'sv': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'cs': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'sk': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'hr': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'sr': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'az': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}, 'sw': {'ollama_off': 'Ollama is off. Run ollama serve.', 'no_session': '{target} does not share a session here. Paste the fixed sentence there. Choose Ollama for local chat.'}}
