"""Kota / usage_client arayüz metinleri — tüm diller."""

METER_TR = {
    "meter.total": "Toplam",
    "meter.pool": "Havuz",
    "meter.credit": "Kredi",
    "meter.quota": "Kota",
    "meter.status": "Durum",
    "meter.5h": "5 saat",
    "meter.weekly": "Haftalık",
    "meter.daily": "Günlük",
    "meter.unlimited": "Sınırsız",
    "meter.no_quota": "Kota yok",
    "meter.completions": "Tamamlama",
    "meter.auto": "Otomatik",
    "meter.api": "API",
    "meter.ondemand": "Talep üzerine",
    "plan.local": "Yerel",
    "plan.individual": "Bireysel",
    "plan.plus": "Plus",
    "plan.pro": "Pro",
    "plan.free": "Ücretsiz",
    "plan.team": "Takım",
    "plan.business": "Business",
    "plan.enterprise": "Kurumsal",
    "detail.local_no_internet": "Yerel model, internet kotası yok",
    "detail.credit_balance": "Kredi bakiyesi",
    "detail.tabnine": "Kota API yok; hesap kotası uygulamada",
    "detail.amazon_q": "Kota AWS hesabında, yerel okunamaz",
    "detail.jetbrains": "Kota JetBrains hesabında",
    "detail.aider": "Kota, bağlı API anahtarına göre",
    "detail.groq": "Kota Groq Cloud hesabında",
    "detail.qwen": "Kota sağlayıcı hesabında",
    "detail.cline": "Kota, Cline'ın kullandığı modele göre",
    "detail.windsurf_panel": "Kurulu; Windsurf kotası hesap panelinde, token paylaşılmıyor",
    "detail.installed": "Kurulu bulundu",
    "detail.copilot_no_auth": "Kurulu ama GitHub oturumu yok (gh auth login)",
    "detail.copilot_auth_invalid": "GitHub oturumu geçersiz; gh auth login ile yenile",
    "detail.copilot_no_sub": "Bu hesapta Copilot aboneliği yok",
    "detail.no_session_file": "Oturum dosyası yok, kota okunamadı",
    "detail.no_token": "Token yok",
    "detail.chatgpt_login": "Uygulama var; kota için ChatGPT/Codex girişi gerekir",
    "detail.continue": "Kota, Continue'un bağladığı API anahtarına göre",
    "detail.trae": "Kota Trae hesabında, yerel okunamaz",
    "error.timeout": "Zaman aşımı",
    "error.generic": "İşlem tamamlanamadı",
    "error.http": "Sunucu yanıt vermedi",
    "error.network": "Ağ bağlantısı kurulamadı",
    "error.session": "Oturum bulunamadı veya geçersiz",
    "error.auth": "Yetkilendirme başarısız",
    "error.not_found": "Kayıt bulunamadı",
    "reset.resetting": "Yenileniyor",
    "reset.at": "Yenilenme {when}",
    "reset.in_days": "{days}g {hours}s · {when}",
    "reset.in_hours": "{hours}s {mins}dk · {when}",
    "reset.in_mins": "{mins}dk · {when}",
    "fmt.money_left": "{amount} kaldı",
    "fmt.limit": "Limit {amount}",
    "fmt.spend_pair": "{used} / {limit}",
    "fmt.balance": "{amount} bakiye",
}

METER_EN = {
    "meter.total": "Total",
    "meter.pool": "Pool",
    "meter.credit": "Credit",
    "meter.quota": "Quota",
    "meter.status": "Status",
    "meter.5h": "5 hours",
    "meter.weekly": "Weekly",
    "meter.daily": "Daily",
    "meter.unlimited": "Unlimited",
    "meter.no_quota": "No quota",
    "meter.completions": "Completions",
    "meter.auto": "Auto",
    "meter.api": "API",
    "meter.ondemand": "On-demand",
    "plan.local": "Local",
    "plan.individual": "Individual",
    "plan.plus": "Plus",
    "plan.pro": "Pro",
    "plan.free": "Free",
    "plan.team": "Team",
    "plan.business": "Business",
    "plan.enterprise": "Enterprise",
    "detail.local_no_internet": "Local model, no internet quota",
    "detail.credit_balance": "Credit balance",
    "detail.tabnine": "No quota API; account quota in app",
    "detail.amazon_q": "Quota on AWS account, not readable locally",
    "detail.jetbrains": "Quota on JetBrains account",
    "detail.aider": "Quota depends on connected API key",
    "detail.groq": "Quota on Groq Cloud account",
    "detail.qwen": "Quota on provider account",
    "detail.cline": "Quota depends on model Cline uses",
    "detail.windsurf_panel": "Installed; Windsurf quota in account panel, no token shared",
    "detail.installed": "Installed",
    "detail.copilot_no_auth": "Installed but no GitHub session (gh auth login)",
    "detail.copilot_auth_invalid": "GitHub session invalid; refresh with gh auth login",
    "detail.copilot_no_sub": "No Copilot subscription on this account",
    "detail.no_session_file": "No session file, quota unreadable",
    "detail.no_token": "No token",
    "detail.chatgpt_login": "App found; ChatGPT/Codex login required for quota",
    "detail.continue": "Quota depends on API key Continue uses",
    "detail.trae": "Quota on Trae account, not readable locally",
    "error.timeout": "Timeout",
    "error.generic": "Could not complete the action",
    "error.http": "Server did not respond",
    "error.network": "Network connection failed",
    "error.session": "Session missing or invalid",
    "error.auth": "Authorization failed",
    "error.not_found": "Not found",
    "reset.resetting": "Resetting",
    "reset.at": "Resets {when}",
    "reset.in_days": "{days}d {hours}h · {when}",
    "reset.in_hours": "{hours}h {mins}m · {when}",
    "reset.in_mins": "{mins}m · {when}",
    "fmt.money_left": "{amount} left",
    "fmt.limit": "Limit {amount}",
    "fmt.spend_pair": "{used} / {limit}",
    "fmt.balance": "{amount} balance",
}

# ponytail: EN tabanlı kısa çeviriler; tam lokalizasyon gerekirse lang_packs_data'ya taşınır
_LOCAL = {
    "es": {
        "meter.total": "Total", "meter.pool": "Pool", "meter.credit": "Credito", "meter.quota": "Cuota",
        "meter.status": "Estado", "meter.5h": "5 horas", "meter.weekly": "Semanal", "meter.daily": "Diario",
        "meter.unlimited": "Ilimitado", "meter.no_quota": "Sin cuota", "meter.completions": "Completados",
        "plan.local": "Local",
        "detail.local_no_internet": "Modelo local, sin cuota de internet",
        "detail.credit_balance": "Saldo de credito",
        "detail.tabnine": "Sin API de cuota; cuota en la app",
        "detail.amazon_q": "Cuota en cuenta AWS, no legible localmente",
        "detail.jetbrains": "Cuota en cuenta JetBrains",
        "detail.aider": "Cuota segun clave API conectada",
        "detail.groq": "Cuota en cuenta Groq Cloud",
        "detail.qwen": "Cuota en cuenta del proveedor",
        "detail.cline": "Cuota segun modelo que usa Cline",
        "detail.windsurf_panel": "Instalado; cuota Windsurf en panel de cuenta",
        "detail.installed": "Instalado",
        "detail.copilot_no_auth": "Instalado pero sin sesion GitHub (gh auth login)",
        "detail.no_session_file": "Sin archivo de sesion, cuota ilegible",
        "detail.no_token": "Sin token",
        "detail.chatgpt_login": "App encontrada; inicio ChatGPT/Codex requerido",
        "detail.continue": "Cuota segun clave API de Continue",
        "detail.trae": "Cuota en cuenta Trae, no legible localmente",
        "error.timeout": "Tiempo agotado",
        "reset.resetting": "Renovando",
        "reset.at": "Renueva {when}",
        "reset.in_days": "{days}d {hours}h · {when}",
        "reset.in_hours": "{hours}h {mins}m · {when}",
        "reset.in_mins": "{mins}m · {when}",
        "fmt.money_left": "{amount} restante",
        "fmt.limit": "Limite {amount}",
        "fmt.spend_pair": "{used} / {limit}",
        "fmt.balance": "{amount} saldo",
    },
    "pt": {
        "meter.total": "Total", "meter.pool": "Pool", "meter.credit": "Credito", "meter.quota": "Cota",
        "meter.status": "Estado", "meter.5h": "5 horas", "meter.weekly": "Semanal", "meter.daily": "Diario",
        "meter.unlimited": "Ilimitado", "meter.no_quota": "Sem cota", "meter.completions": "Completos",
        "plan.local": "Local",
        "detail.local_no_internet": "Modelo local, sem cota de internet",
        "detail.credit_balance": "Saldo de credito",
        "error.timeout": "Tempo esgotado", "reset.resetting": "Renovando",
        "reset.at": "Renova {when}",
        "reset.in_days": "{days}d {hours}h · {when}",
        "reset.in_hours": "{hours}h {mins}m · {when}",
        "reset.in_mins": "{mins}m · {when}",
        "fmt.money_left": "{amount} restante",
        "fmt.limit": "Limite {amount}",
        "fmt.spend_pair": "{used} / {limit}",
        "fmt.balance": "{amount} saldo",
        "detail.installed": "Instalado",
        "detail.no_token": "Sem token",
        "detail.no_session_file": "Sem arquivo de sessao",
    },
    "ar": {
        "meter.total": "الإجمالي", "meter.pool": "المجمع", "meter.credit": "رصيد", "meter.quota": "حصة",
        "meter.status": "الحالة", "meter.5h": "5 ساعات", "meter.weekly": "أسبوعي", "meter.daily": "يومي",
        "meter.unlimited": "غير محدود", "meter.no_quota": "لا حصة", "plan.local": "محلي",
        "detail.local_no_internet": "نموذج محلي، لا حصة إنترنت",
        "error.timeout": "انتهى الوقت", "reset.resetting": "جاري التجديد",
        "reset.at": "يتجدد {when}",
        "fmt.money_left": "متبقي {amount}",
        "fmt.limit": "حد {amount}",
        "fmt.balance": "رصيد {amount}",
    },
    "zh": {
        "meter.total": "总计", "meter.pool": "池", "meter.credit": "积分", "meter.quota": "配额",
        "meter.status": "状态", "meter.5h": "5小时", "meter.weekly": "每周", "meter.daily": "每日",
        "meter.unlimited": "无限", "meter.no_quota": "无配额", "plan.local": "本地",
        "detail.local_no_internet": "本地模型，无网络配额",
        "error.timeout": "超时", "reset.resetting": "重置中",
        "reset.at": "重置 {when}",
        "fmt.money_left": "剩余 {amount}",
        "fmt.limit": "限额 {amount}",
        "fmt.balance": "{amount} 余额",
    },
    "ja": {
        "meter.total": "合計", "meter.pool": "プール", "meter.credit": "クレジット", "meter.quota": "クォータ",
        "meter.status": "状態", "meter.5h": "5時間", "meter.weekly": "週次", "meter.daily": "日次",
        "meter.unlimited": "無制限", "meter.no_quota": "クォータなし", "plan.local": "ローカル",
        "detail.local_no_internet": "ローカルモデル、インターネットクォータなし",
        "error.timeout": "タイムアウト", "reset.resetting": "更新中",
        "reset.at": "更新 {when}",
        "fmt.money_left": "残り {amount}",
        "fmt.limit": "上限 {amount}",
        "fmt.balance": "{amount} 残高",
    },
    "ko": {
        "meter.total": "합계", "meter.pool": "풀", "meter.credit": "크레딧", "meter.quota": "할당량",
        "meter.status": "상태", "meter.5h": "5시간", "meter.weekly": "주간", "meter.daily": "일간",
        "meter.unlimited": "무제한", "meter.no_quota": "할당량 없음", "plan.local": "로컬",
        "detail.local_no_internet": "로컬 모델, 인터넷 할당량 없음",
        "error.timeout": "시간 초과", "reset.resetting": "갱신 중",
        "reset.at": "갱신 {when}",
        "fmt.money_left": "{amount} 남음",
        "fmt.limit": "한도 {amount}",
        "fmt.balance": "{amount} 잔액",
    },
}

METER: dict[str, dict[str, str]] = {"tr": METER_TR, "en": METER_EN}
for code, partial in _LOCAL.items():
    pack = dict(METER_EN)
    pack.update(partial)
    METER[code] = pack
for code in (
    "fa", "hi", "bn", "ur", "vi", "ms", "sv", "cs", "sk", "hr", "sr", "az", "sw",
):
    if code not in METER:
        METER[code] = dict(METER_EN)
