# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ["overlay.py"],
    pathex=["."],
    binaries=[],
    datas=[("logo.png", "."), ("logo.ico", "."), ("assets/flags", "assets/flags")],
    hiddenimports=["usage_client", "prompt_coach", "lang_packs", "lang_packs_data", "meter_texts", "platform_util"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "test_buttons",
        "test_privacy",
        "test_license",
        "PySide6.QtQml",
        "PySide6.QtQuick",
        "PySide6.QtQuickWidgets",
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebEngineQuick",
        "PySide6.Qt3DCore",
        "PySide6.QtPdf",
        "PySide6.QtDesigner",
        "PySide6.QtTest",
        "PySide6.QtBluetooth",
        "PySide6.QtNfc",
        "PySide6.QtMultimedia",
        "PySide6.QtLocation",
        "PySide6.QtPositioning",
        "PySide6.QtSensors",
        "PySide6.QtTextToSpeech",
        "PySide6.QtCharts",
        "PySide6.QtDataVisualization",
        "PySide6.QtGraphs",
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="TokenTracker",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    icon="logo.ico",
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    name="TokenTracker",
    strip=False,
    upx=False,
    upx_exclude=[],
)
